/*
 * Program je s��as�ou syst�mu EaSys V1
 * Each line should be prefixed with  * 
 */

package eoc.xinterface;

import eoc.database.DBconnection;
import java.sql.Connection;

/**
 *
 * @author rvanya
 */
public class XTB_vyber extends eoc.xinterface.XTable {

    /**
     * Creates new form DBT_XTB_vyber
     */
    public XTB_vyber() {
        initComponents();
    }
   @Override
   public String initialize(system.Kernel kr, DBconnection cX) {
      this.setConn(cX);
      this.setKrn(kr);
      this.setXTableType("DBTABLE");
      this.setMyTable(jTable1);
      this.setMyScrollPane(jScrollPane1);
      // Sybase
      //this.setMasterTable("osoby");
      //this.setMasterKey("id");
      //this.setMasterKeyDataType("INTEGER");
      //this.setDisplayedFields("id,meno,priez,rodmeno,dtnarod,rodcislo");
      //this.setQueryBase("select * from osoby");
       
      // Postgres
      //this.setMasterTable("eas_usrgrp");
     // this.setMasterKey("id_eas_usrgrp","INTEGER");
      //this.setDisplayedFields("id_eas_usrgrp,c_group^Skupina,c_popis^Popis,c_private_data,c_poznamka");
      //this.setQueryBase("select * from eas_usrgrp");
      // this.setAppWhere("1=0"); // prazdne query
      // this.setAppWhere("id_eas_users < 50000");
      super.initialize(kr,cX);
      this.setiNumFetchedRows(60);
      return "";
   }

   
//       @Override
    public void rowDblClicked() {
      //  super.rowDblClicked(); //To change body of generated methods, choose Tools | Templates.
       System.out.println("rowDblClicked()_IN_XTB_vyber");
//        rowViewerXDObjectSource.viewRowViewer("ULOHY","");

    }

   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
