/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package system;

import eoc.database.DBconnection;
import system.desktop.Desktop;
import system.Kernel;
import java.awt.AWTEvent;
import java.awt.Component;
import java.awt.Dialog;
import java.awt.EventQueue;
import java.awt.Frame;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.MouseEvent;
import java.awt.event.WindowEvent;
import java.lang.reflect.Method;
import java.sql.Connection;
import java.util.Hashtable;

/**
 *
 * @author rvanya
 */
public class Vyber extends eoc.widgets.DObject {

   private Desktop     dsk;
   private eoc.IEOC_VisualObject questor_frm;
   private Component   questor_fld;
   // ziadana navratova hodnota s moze skladat z dvoch casti, delenych ^
   // pricom prva cast moze skladat z casti delenych ciarkou,
   // druha cast MUSI BIT nazov jedneho stlca 
   // (nieco, ako primary_key vyberu, z hladiska objektu-ziadatela)
   // Vsetky casti MUSIA byt nazvami stlpcov z tabulky vyberu
   private String[] sRetValCols;
   private String   sRequiedPrimaryKey;
   private String   sRetVal = "";
   private Object /* eoc.IEOC_VisualObject */ methodSource;
////   Hashtable<String, Method> htCalcMethods = new Hashtable<String, Method>();

    public Vyber(Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setAlwaysOnTop(true);
    }

   /**
    * Creates new form EOC_vyber
    */
   /*
   public EOC_vyber() {
      initComponents();
      this.setModalExclusionType(Dialog.ModalExclusionType.APPLICATION_EXCLUDE );
      setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);
 }
   */
   
    @Override
    public String initialize(Kernel krnl, DBconnection cX) {
       super.initialize(krnl, cX);
       krn = krnl;
       MyCn = cX;
       dsk = krn.getDsk();
       dsk.setEnabled(false);
       bInitialized = true;
       xTB_vyber1.setParentContainer(this);
       return "";
    }

   /**
    * This method is called from within the constructor to initialize the form. WARNING:
    * Do NOT modify this code. The content of this method is always regenerated by the
    * Form Editor.
    */
   @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_OK = new javax.swing.JButton();
        btn_Zrus = new javax.swing.JButton();
        xTB_vyber1 = new system.XTB_vyber();

        setTitle("Výber");
        setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        btn_OK.setText("OK");
        btn_OK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_OKActionPerformed(evt);
            }
        });

        btn_Zrus.setText("Zruš");
        btn_Zrus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ZrusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(207, Short.MAX_VALUE)
                .addComponent(btn_OK)
                .addGap(35, 35, 35)
                .addComponent(btn_Zrus)
                .addContainerGap(207, Short.MAX_VALUE))
            .addComponent(xTB_vyber1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(xTB_vyber1, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Zrus)
                    .addComponent(btn_OK))
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(561, 453));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

   private void btn_ZrusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ZrusActionPerformed
      sRetVal = "<CANCELED>";
      endVyber(true /* schovat okno */);
      
      this.processWindowEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
   }//GEN-LAST:event_btn_ZrusActionPerformed

   private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
      //// krn.krnMsg("formWindowClosed"); 
      dsk.setEnabled(true);
   }//GEN-LAST:event_formWindowClosed

   
   private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
      dsk.setEnabled(true);
      // ked ma sRetVal hodnotu, bola nastavena buttonmi OK alebo Zrus
      if (sRetVal.equals("")) {
         sRetVal = "<CANCELED>";
         endVyber(false);
      }
   }//GEN-LAST:event_formWindowClosing
   /*
   private String[] sRetValCols;
   private String   sRequiedPrimaryKey;
   private String   sRetVal = "";
   */
   private String packRetVal() {
       sRetVal = "";
       for(int i=0; i<sRetValCols.length; i++) {
           System.out.println("packRetValLLLfor: " + sRetValCols[i]);
           sRetVal = sRetVal + "," 
                   + xTB_vyber1.getScreenValue(sRetValCols[i]);
       }
       if (sRetVal.startsWith(",")) sRetVal = sRetVal.substring(1);
       if (!sRequiedPrimaryKey.equals(""))
           sRetVal = sRetVal + "^" 
                   + xTB_vyber1.getScreenValue(sRequiedPrimaryKey);
       if (krn.getVerboseLevel() < 6)
           krn.Message("Vyber.packRetVal() returning: " + sRetVal);
       return sRetVal;
   };
   
   private void btn_OKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_OKActionPerformed
       ////krn.krnMsg("EKSN_PERFORMED");
       OK_pressed();
   }//GEN-LAST:event_btn_OKActionPerformed

   public void OK_pressed() {
      sRetVal = packRetVal();
      endVyber(true /* schovat okno */);
   }
   
   public void endVyber(boolean schovatOkno) {
      if (schovatOkno)  {
         this.processWindowEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
      }
      //krn.krnMsg("VYBRALA SA HODNOTA: " + sRetVal);

   }
   /*
   private String[] sRetValCols;
   private String   sRequiedPrimaryKey;
   private String   sRetVal = "";
   */
           
   public String createVyberForMe(eoc.IEOC_VisualObject vFromViewer, Component comp, 
                              String tbl, String msKey, String colDefs, 
                              String retCol, String sWhere, String sOrder,
                              String sTitle) { 
      String sFirstRetvalPart;
      sFirstRetvalPart = system.FnEaS.sEntry(1, retCol, "^");
      if (system.FnEaS.iNumEntries(retCol,"^") > 1) 
          sRequiedPrimaryKey = system.FnEaS.sEntry(2, retCol, "^") ;
      else 
          sRequiedPrimaryKey = "";
      sRetValCols  = sFirstRetvalPart.split(",");
      questor_frm = vFromViewer;
      questor_fld = comp;
      
      // inicializacia objektu eOC_XTB_vyber
      xTB_vyber1.setConn(MyCn);
      xTB_vyber1.setKrn(krn);
      xTB_vyber1.setXTableType("DBTABLE");
      xTB_vyber1.setMasterTable(tbl);
      xTB_vyber1.setMasterKey(msKey,"INTEGER");
      xTB_vyber1.setDisplayedFields(colDefs);
      xTB_vyber1.setMethodSource(methodSource);
////      put_htMethods(vFromViewer, getMetodNamesFromColDef(colDefs), htCalcMethods, true /* clear */);
      xTB_vyber1.setQueryBase("select * from " + tbl);
      // this.setAppWhere("1=0"); // prazdne query
      // this.setAppWhere("id_eas_users < 50000");
////      System.out.println("SETTTINGWHERETOO:" + sWhere);
      if (sWhere.length() > 0)
          xTB_vyber1.setAppWhere(sWhere);
      xTB_vyber1.setOrderKey(sOrder, "string");
      xTB_vyber1.setiNumFetchedRows(-9999);
      /////krn.OutPrintln("BLAAAABL\n" + krn.toString() + "\n" + CnEx.toString() + "\n" + CnIn.toString() + "\n" + sMyCn);
      xTB_vyber1.setParentContainer(this);
      xTB_vyber1.initialize(krn,MyCn);
      if (sTitle.length() > 0)
          this.setTitle(sTitle);
      this.setVisible(true);
      return sRetVal;
   }

   public String createQVyberForMe(eoc.IEOC_VisualObject vFromViewer, Component comp, 
                              String tbl, String msKey, String sQry, 
                              String retCol, String sWhere, String sOrder,
                              String sTitle,String sHeaders) { 
      String sFirstRetvalPart;
      sFirstRetvalPart = system.FnEaS.sEntry(1, retCol, "^");
      if (system.FnEaS.iNumEntries(retCol,"^") > 1) 
          sRequiedPrimaryKey = system.FnEaS.sEntry(2, retCol, "^") ;
      else 
          sRequiedPrimaryKey = "";
      sRetValCols  = sFirstRetvalPart.split(",");
      questor_frm = vFromViewer;
      questor_fld = comp;
      
      // inicializacia objektu eOC_XTB_vyber
      xTB_vyber1.setConn(MyCn);
      xTB_vyber1.setKrn(krn);
      xTB_vyber1.setXTableType("DBTABLE");
      xTB_vyber1.setMasterTable(tbl);
      xTB_vyber1.setMasterKey(msKey,"INTEGER");
      xTB_vyber1.setDisplayedFields(sHeaders);
      xTB_vyber1.setMethodSource(methodSource);
////      put_htMethods(vFromViewer, getMetodNamesFromColDef(colDefs), htCalcMethods, true /* clear */);
      xTB_vyber1.setFullQuery(sQry);
    ////  pri setFullQuery(sQry) by sa mali asi inak interpretovat parametre - hlavne sHeaders
      // this.setAppWhere("1=0"); // prazdne query
      // this.setAppWhere("id_eas_users < 50000");
////      System.out.println("SETTTINGWHERETOO:" + sWhere);
      xTB_vyber1.setiNumFetchedRows(-9999);
      /////krn.OutPrintln("BLAAAABL\n" + krn.toString() + "\n" + CnEx.toString() + "\n" + CnIn.toString() + "\n" + sMyCn);
      xTB_vyber1.setParentContainer(this);
      xTB_vyber1.initialize(krn,MyCn);
      if (sTitle.length() > 0)
          this.setTitle(sTitle);
      this.setVisible(true);
      return sRetVal;
   }

   public String getMetodNamesFromColDef (String cd) {
       cd = cd.trim();
       System.out.println("Getting mtdn from: " + cd);
       String cdfs[] = cd.split("~");
       String mtn = "";
       String mn;
       for (String s: cdfs) {
           mn = s.trim();
           if (mn.startsWith("FUN@")) {
               mtn = mtn + "," + FnEaS.sEntry(1,mn.substring(3),"^");
           }
           //// else System.out.println("MIAFASZEZ?:" + mn);
       }
       if (mtn.length() > 0) mtn = mtn.substring(1); // odrezanie prevej ciarky
       System.out.println("getMetodNamesFromColDefRETURN:" + mtn);
       return mtn;
   }
/*   
    public void put_htMethods(eoc.IEOC_VisualObject findInObject ,String mtdNames,
            Hashtable<String, Method> ht, boolean bClear) {
        if (bClear) ht.clear();
        
    }
*/
   
    @Override
    public String receiveMessage(eoc.EOC_message eocMsg) {

        // musi byt ako prva instrukcia v metode !!!
        if (eocMsg==null) return FnEaS.nullEocMessageResponse(myObjectID);
        
        /////krn.krnMsg("receivingdblclick_message = " + sMessage);
        String receive_status = null;
        try {
             receive_status = 
                super.receiveMessage(eocMsg); 
        }
        catch (Exception ex) {
            // ked metoda neexistuje, spracuje sa to nizsie
       }
       if (eocMsg.getMessage().equalsIgnoreCase("MOUSE_DOUBLE_CLICKED")) {
           btn_OK.doClick();
         /* 
        krn.krnMsg("receivingdblclick_message >>>> ACTIOOOON-01 --> " + btn_OK.getX() + " - " + btn_OK.getY());
           ActionEvent aevt =
               new ActionEvent((Object)btn_OK, ActionEvent.ACTION_PERFORMED, "MOUSE_CLICKED");
        EventQueue q = Toolkit.getDefaultToolkit().getSystemEventQueue();
        EventQueue qn = new EventQueue();
        synchronized(q) {
           q.postEvent(aevt);
           enableEvents(AWTEvent.MOUSE_EVENT_MASK);
           MouseEvent me;
           me = new MouseEvent((Component)btn_OK, MouseEvent.MOUSE_CLICKED, 
                            1, MouseEvent.BUTTON1, btn_OK.getX() + 1, btn_OK.getY() + 1, 1, false);
           q.postEvent(me);
           q.push(qn);
           
        }
        */
        ////krn.krnMsg("receivingdblclick_message >>>> ACTIOOOON-02");
       }
       return "";
    }
   public String getRetVal() {
      sRetVal = packRetVal();
      return sRetVal;
   }
    public void setMethodSource(Object mtdSrc) {
        methodSource = mtdSrc;
    }

    /**
  * @param args the command line arguments
  */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_OK;
    private javax.swing.JButton btn_Zrus;
    private system.XTB_vyber xTB_vyber1;
    // End of variables declaration//GEN-END:variables
}
