/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package system;

import eoc.IEOC_DB_driver;
import eoc.database.DBconnection;
import eoc.dbdrv.DbDrv_Firebird;
import eoc.dbdrv.DbDrv_MySQL;
import eoc.dbdrv.DbDrv_Postgres;
import eoc.dbdrv.DbDrv_Sybase;
import java.awt.AWTEvent;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.JDialog;

/**
 *
 * @author rvanya
 */
public class Welcome_panel_simple extends eoc.widgets.PObject {
    boolean committedOK = false;
    eoc.IEOC_VisualObject parentContainer; 
    private boolean bMode = false; // simple(true)/advanced(false)
    Map<String, String>[] hmFrameValues;
    /**
     * Creates new form EaS_welcome_pnl
     */
    public Welcome_panel_simple() {
        initComponents();
        eOC_DBconnectWork.setConnType("Pracovná databáza","WORK");
    }
    @Override
    public String initialize(Kernel kr, DBconnection cX) {
        super.initialize(kr, cX); //To change body of generated methods, choose Tools | Templates.
        File f = new File(krn.getParentDirectory() + "/EaSys/sys/easys/FirmBanner.png");
////        System.out.println("TOTOKEXISTUJE:" + krn.getParentDirectory() + "/EaSys/sys/easys/FirmBanner.png"
////                +  " " + (f==null));
        if (!(f==null)) {
            /* 2015-5-13
          Icon imgFirmBanner = new javax.swing.ImageIcon(
                getClass().getResource("sys//easys//FirmBanner.png"));
            */
          Icon imgFirmBanner = new javax.swing.ImageIcon(krn.getParentDirectory() + "/EaSys/sys/easys/FirmBanner.png");
            lblBanner.setIcon(imgFirmBanner);
        } 
//        String savedFrame;
//        savedFrame = krn.getStanicaUserAttribute("Connection_frame_WORK");
        eOC_DBconnectWork.setDBselection("Sybase");
        eOC_DBconnectWork.setParentContainer(parentContainer);
////       System.out.println("> > > > > INIT_A");
        eOC_DBconnectWork.initFromFromSaved();
////      System.out.println("> > > > > INIT_B");
        
        initFirmBanner();
        return "";
    }
/*
*/
    public String initFirmBanner() {
        File f = new File(krn.getParentDirectory() + "/EaSys/sys/easys/FirmBanner.png");
        if (!(f==null)) {
          Icon imgFirmBanner = 
               new javax.swing.ImageIcon(krn.getParentDirectory() + "/EaSys/sys/easys/FirmBanner.png");
           lblBanner.setIcon(imgFirmBanner);
        } 
        return "";
    }

    
    public String setKrn(Kernel krnl) {
        krn = krnl;
        //lblAppName.setText(krn.getAppName());
        lblAppVersion.setText(krn.getAppVersion());
        lblAppDescription.setText(krn.getAppDescription());
        eOC_DBconnectWork.setKrn(krn);
        return "";
        
    }
        
    public DBconnection[] getDedicatedDBConnections(boolean bAutoconnect) {
        ////krn.OutPrintln("pnl-requirong start");
        DBconnection[] cnx = {null,null,null};
        cnx[0] = eOC_DBconnectWork.getDBconnection(bAutoconnect);
        return cnx;
    }

    public IEOC_DB_driver[] getDedicatedDBdrivers(boolean bAutoconnect) {
        ////krn.OutPrintln("pnl-requirong start");
        IEOC_DB_driver[] cnx = {null,null,null};
        cnx[0] = getDbDriver(eOC_DBconnectWork.getDBconnection(bAutoconnect));
        return cnx;
    }
    
    public IEOC_DB_driver getDbDriver(DBconnection dbc) {
        IEOC_DB_driver drv = null;
        if (dbc.getDBType().toUpperCase().equals("SYBASE"))
                drv = new DbDrv_Sybase();
        else if (dbc.getDBType().toUpperCase().equals("FIREBIRD"))
                drv = new DbDrv_Firebird();
        else if (dbc.getDBType().toUpperCase().equals("MySQL"))
                drv = new DbDrv_MySQL();
        else if (dbc.getDBType().toUpperCase().equals("POSTGRES"))
                drv = new DbDrv_Postgres();
        return drv;
    }
   
    /**
     * This method is called from within the constructor to initialize the form. WARNING:
     * Do NOT modify this code. The content of this method is always regenerated by the
     * Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBanner = new javax.swing.JLabel();
        eOC_DBconnectWork = new eoc.database.Pnl_DBconnect();
        lblAppVersion = new javax.swing.JLabel();
        lblAppDescription = new javax.swing.JLabel();
        lblAppName = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnSave = new javax.swing.JButton();

        setAutoscrolls(true);

        lblBanner.setFont(new java.awt.Font("Lucida Console", 1, 14)); // NOI18N
        lblBanner.setForeground(new java.awt.Color(153, 0, 153));
        lblBanner.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBanner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/easys/res/img/Logo_V1_aa.png"))); // NOI18N

        eOC_DBconnectWork.setName("internalDBconnect"); // NOI18N

        lblAppVersion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblAppVersion.setText("<verzia>");
        lblAppVersion.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        lblAppDescription.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        lblAppDescription.setText("<popis verzie>");

        lblAppName.setIcon(new javax.swing.ImageIcon(getClass().getResource("/easys/res/img/EaSysV2.png"))); // NOI18N
        lblAppName.setToolTipText("The Easy Applicable System");

        btnSave.setText("Pokračuj");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(btnSave)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lblAppName, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblAppVersion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lblAppDescription, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(eOC_DBconnectWork, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 792, Short.MAX_VALUE)
                    .addComponent(lblBanner, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAppName, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAppVersion, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAppDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblBanner, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(eOC_DBconnectWork, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        DBconnection[] cnx;
        cnx = getDedicatedDBConnections(true);
        if (cnx[0].getConn()==null) {
            Kernel.staticMsg("Pracovnú databázu sa nepodarilo pripojiť.");
           // Kernel.Msg(this.getParent().gtt());
        }
        /*
        try {
            krn.setDBconn(cnx[0], cnx[1], cnx[2]);
        } catch (IOException ex) {
            Logger.getLogger(Welcome_panel_simple.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Welcome_panel_simple.class.getName()).log(Level.SEVERE, null, ex);
        }
                */
//        Map<String, String>[] fvl = new Map[3];
        //fvl = {{null,null},{null,null},{null,null}};
//        fvl = getFrameValues();
        hmFrameValues[0] = eOC_DBconnectWork.saveFrameToDef();

        committedOK = true;
        this.destroy();
    }//GEN-LAST:event_btnSaveActionPerformed

    @Override
    public String destroy() {
        return parentContainer.destroy(); //To change body of generated methods, choose Tools | Templates.
    }

    public void setMode(boolean mode) {
       bMode = mode; // simple/advanced

    }
    
    public void setReturnMap(Map<String, String>[] hmFrmValues) {
      //// System.out.println("SETTINGRETURNMAP_TO:" + hmFrmValues.length);
       hmFrameValues = hmFrmValues; 
    };
    
    @Override
    public void setParentContainer(eoc.IEOC_VisualObject cntnr) {
       parentContainer = cntnr;  
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private eoc.database.Pnl_DBconnect eOC_DBconnectWork;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAppDescription;
    private javax.swing.JLabel lblAppName;
    private javax.swing.JLabel lblAppVersion;
    private javax.swing.JLabel lblBanner;
    // End of variables declaration//GEN-END:variables
}
