/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package eoc.messages;

import eoc.IEOC_chat;
import java.awt.Color;
import java.awt.Dimension;
import javax.swing.JSplitPane;
import system.Kernel;

/**
 *
 * @author rvanya
 */
public class Pnl_chat extends eoc.widgets.PObject implements IEOC_chat {

    private String[] layerStrings = { "Yellow (0)", "Magenta (1)","Cyan (2)", "Red (3)","Green (4)" };
    private Color[] layerColors = { Color.yellow, Color.magenta, Color.cyan, Color.red, Color.green };
    private Dimension oldSize;
    private Dimension newSize;
    private Dimension dSplitDim;
    private boolean bMinimized = false;
    private int lastDividerLocation;
    private JSplitPane mySplitPnl;
    public Kernel krn;    
    
    ////private JTextArea textArea1;
    ////private JTextArea textArea2;
    ////private JTextArea textArea3;
    
   /**
    * Creates new form EOC_messages
    */
   public Pnl_chat() {
      initComponents();
      oldSize = this.getSize();
    ////  textArea1 = new JTextArea();
    ////  textArea2 = new JTextArea();
    ////  textArea3 = new JTextArea();
////      jPanel_spravy.add(textArea1);
    ////  jPanel_udalosti.add(textArea2);
    ////  jPanel_poznamky.add(textArea3);
////      textArea1.setVisible(true);
    ////  textArea2.setVisible(true);
    ////  textArea3.setVisible(true);
      
      //textArea1.setBackground(layerColors[i]);
      for (int i= 0; i < buttonGroup2.getButtonCount(); i++) {
      jTextArea_spravy.setText(jTextArea_spravy.getText() + " " + Integer.toString(i));
//      jLayeredPane1.add(textArea, i);
      }              
      jTextArea_udalosti.setText("");
      jRadioButton1.doClick();
   }
    @Override
   public void addLogRow(String rw) {
//       krn.OutPrintln("sdding log_row: " + rw);
//       jTextArea_udalosti.setText(jTextArea_udalosti.getText() + "\n" + rw);
       jTextArea_udalosti.append(rw + "\n");
   }
   /**
    * This method is called from within the constructor to initialize the form. WARNING:
    * Do NOT modify this code. The content of this method is always regenerated by the
    * Form Editor.
    */
   @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup2 = new javax.swing.ButtonGroup();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jPanel_main = new javax.swing.JPanel();
        jPanel_spravy = new javax.swing.JPanel();
        jScrollPane_spravy = new javax.swing.JScrollPane();
        jTextArea_spravy = new javax.swing.JTextArea();
        jPanel_udalosti = new javax.swing.JPanel();
        jScrollPane_udalosti = new javax.swing.JScrollPane();
        jTextArea_udalosti = new javax.swing.JTextArea();
        jPanel_poznamky = new javax.swing.JPanel();
        jScrollPane_poznamky = new javax.swing.JScrollPane();
        jTextArea_poznamky = new javax.swing.JTextArea();

        buttonGroup2.add(jRadioButton1);
        jRadioButton1.setText("Správy");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup2.add(jRadioButton2);
        jRadioButton2.setText("Udalosti");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        buttonGroup2.add(jRadioButton3);
        jRadioButton3.setText("Poznámky");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/easys/res/img/DOWN_U.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel_main.setLayout(new javax.swing.BoxLayout(jPanel_main, javax.swing.BoxLayout.Y_AXIS));

        jPanel_spravy.setBackground(new java.awt.Color(204, 255, 255));
        jPanel_spravy.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTextArea_spravy.setColumns(20);
        jTextArea_spravy.setRows(5);
        jScrollPane_spravy.setViewportView(jTextArea_spravy);

        javax.swing.GroupLayout jPanel_spravyLayout = new javax.swing.GroupLayout(jPanel_spravy);
        jPanel_spravy.setLayout(jPanel_spravyLayout);
        jPanel_spravyLayout.setHorizontalGroup(
            jPanel_spravyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane_spravy, javax.swing.GroupLayout.DEFAULT_SIZE, 493, Short.MAX_VALUE)
        );
        jPanel_spravyLayout.setVerticalGroup(
            jPanel_spravyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane_spravy, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
        );

        jPanel_main.add(jPanel_spravy);

        jPanel_udalosti.setBackground(new java.awt.Color(212, 254, 212));
        jPanel_udalosti.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel_udalosti.setForeground(new java.awt.Color(204, 255, 204));

        jTextArea_udalosti.setColumns(20);
        jTextArea_udalosti.setRows(5);
        jScrollPane_udalosti.setViewportView(jTextArea_udalosti);

        javax.swing.GroupLayout jPanel_udalostiLayout = new javax.swing.GroupLayout(jPanel_udalosti);
        jPanel_udalosti.setLayout(jPanel_udalostiLayout);
        jPanel_udalostiLayout.setHorizontalGroup(
            jPanel_udalostiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane_udalosti, javax.swing.GroupLayout.DEFAULT_SIZE, 493, Short.MAX_VALUE)
        );
        jPanel_udalostiLayout.setVerticalGroup(
            jPanel_udalostiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane_udalosti, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
        );

        jPanel_main.add(jPanel_udalosti);

        jPanel_poznamky.setBackground(new java.awt.Color(255, 255, 204));
        jPanel_poznamky.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTextArea_poznamky.setColumns(20);
        jTextArea_poznamky.setRows(5);
        jScrollPane_poznamky.setViewportView(jTextArea_poznamky);

        javax.swing.GroupLayout jPanel_poznamkyLayout = new javax.swing.GroupLayout(jPanel_poznamky);
        jPanel_poznamky.setLayout(jPanel_poznamkyLayout);
        jPanel_poznamkyLayout.setHorizontalGroup(
            jPanel_poznamkyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane_poznamky, javax.swing.GroupLayout.DEFAULT_SIZE, 493, Short.MAX_VALUE)
        );
        jPanel_poznamkyLayout.setVerticalGroup(
            jPanel_poznamkyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane_poznamky, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
        );

        jPanel_main.add(jPanel_poznamky);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel_main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jRadioButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton2)
                        .addGap(2, 2, 2)
                        .addComponent(jRadioButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_main, javax.swing.GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
     //jLayeredPane1.setLayer(jLayeredPane1.getComponentsInLayer(0)[0],0);
        
        jPanel_spravy.setVisible(true);
        jPanel_udalosti.setVisible(false);
        jPanel_poznamky.setVisible(false);
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
     // jLayeredPane1.setLayer(jLayeredPane1.getComponentsInLayer(1)[0],1);
        jPanel_spravy.setVisible(false);
        jPanel_udalosti.setVisible(true);
        jPanel_poznamky.setVisible(false);
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
    // jLayeredPane1.setLayer(jLayeredPane1.getComponentsInLayer(2)[0],2);
        jPanel_spravy.setVisible(false);
        jPanel_udalosti.setVisible(false);
        jPanel_poznamky.setVisible(true);
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (!bMinimized) {
            mySplitPnl = (JSplitPane) this.getParent();
            dSplitDim = mySplitPnl.getSize();
            //JSplitPane myMasterSplitPnl = (JSplitPane) mySplitPnl.getParent();
            lastDividerLocation = mySplitPnl.getDividerLocation();
            mySplitPnl.setDividerLocation(dSplitDim.height - 80);
            mySplitPnl.repaint();
            mySplitPnl.revalidate();
            //myMasterSplitPnl.repaint();
            //myMasterSplitPnl.revalidate();
            bMinimized = true;
//            jButton1.setText("/\\");
            jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/easys/res/img//UP_U.png"))); // NOI18N
        }
        else {
            mySplitPnl.setDividerLocation(lastDividerLocation);
    //        jButton1.setText("\\/");
            jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/easys/res/img/DOWN_U.png"))); // NOI18N
            bMinimized = false;

        }
        //JOptionPane.showMessageDialog(null,  this.getParent().toString() + "\n\n"
            //        + this.getParent().getSize().toString() + "\n\n"
            //        + mySplitPnl.getDividerLocation());
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel_main;
    private javax.swing.JPanel jPanel_poznamky;
    private javax.swing.JPanel jPanel_spravy;
    private javax.swing.JPanel jPanel_udalosti;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JScrollPane jScrollPane_poznamky;
    private javax.swing.JScrollPane jScrollPane_spravy;
    private javax.swing.JScrollPane jScrollPane_udalosti;
    private javax.swing.JTextArea jTextArea_poznamky;
    private javax.swing.JTextArea jTextArea_spravy;
    private javax.swing.JTextArea jTextArea_udalosti;
    // End of variables declaration//GEN-END:variables
}
