/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package eoc.messages;

import java.awt.Component;
import javax.swing.JProgressBar;

/**
 *
 * @author rvanya
 */
public class StandardProgressBar extends javax.swing.JPanel /* implements Runnable */{
    String currString; 
    /**
     * Creates new form EOC_StandardProgressBar
     */
    public StandardProgressBar() {
        
        try {
        initComponents();
        progBar.setStringPainted(true);
        progBar.setAlignmentX(JProgressBar.RIGHT_ALIGNMENT);
        }
        catch (Exception ex) {
            System.out.println("StandardProgressBar->exception:" + ex.getMessage());
        }
    }
    
    public void setMessage(String t) {
        //DEBUG System.out.println("PAJTINGG:" + t);
        progBar.setStringPainted(true);
        progBar.setString(currString);
    }
    public void setMessageClear(String t) {
        //DEBUG System.out.println("PAJTINGG:" + t);
        progBar.setMaximum(0);
        progBar.setValue(0);
        progBar.setStringPainted(true);
        progBar.setString(currString);
    }
    public void setActivity(String t, int akt, int max) {
      //  System.out.println("StandardProgressBarrr>>>" + t
      //  + "THREADSTTE::" + Thread.currentThread().getState());
        //if (Thread.currentThread().getState() != Thread.) {  }
        currString = t;
        progBar.setMaximum(max);
        progBar.setValue(akt);
        progBar.setIndeterminate(false);
        progBar.setStringPainted(true);
        progBar.setString(currString);
        progBar.doLayout();
    }

    public void setActivity(int akt, int max) {
        progBar.setMaximum(max);
        progBar.setValue(akt);
////        double perc = (double) akt / (double) max;
////        krn.OutPrintln("perc = " + perc);
        progBar.setStringPainted(true);
        progBar.setString("Čas sa nám míňa, kua ... " +  (int) (((double) akt / (double) max) * 100.00) + " %");
 }

    /**
     * This method is called from within the constructor to initialize the form. WARNING:
     * Do NOT modify this code. The content of this method is always regenerated by the
     * Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        progBar = new javax.swing.JProgressBar();

        setBackground(new java.awt.Color(255, 204, 204));

        progBar.setForeground(new java.awt.Color(153, 153, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(progBar, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(progBar, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar progBar;
    // End of variables declaration//GEN-END:variables
/*
    @Override
    public void run() {
       new StandardProgressBar();       
       progBar.setVisible(true);
       System.out.println(">>>> >>>> >>>>> RUNNING VVIISIBLEEEBARRR");
    }
    */
}
