/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package system.tools.uni_cis;

import eoc.IEOC_Object;
import eoc.database.DBconnection;
import eoc.widgets.PObject;
import java.sql.Connection;
import system.Kernel;

/**
 *
 * @author rvanya
 */
public class pnl_uni_cis extends PObject {
     private String  sTyp_ciselnika;
     private Integer id_ciselnika;
    /**
     * Creates new form pnl_uni_cis
     */
    public pnl_uni_cis(String typ_cis) {
       sTyp_ciselnika = typ_cis;
        initComponents();
    }
    @Override
    public String initialize(Kernel kr, DBconnection cX) {
        System.out.println("INITIALIZING_Pnl_uni_cis");
        setMyObjectID(this);
        Object s = MyCn.getDbDriver().SQL_getQueryValue(MyCn.getConn(), 
                      "select * from eas_uni_cis_def where c_typ_cis = '" 
                      + sTyp_ciselnika + "'", "id_eas_uni_cis_def");
        id_ciselnika = Integer.parseInt(s.toString());
        String initialize = super.initialize(kr, cX);
        if (!initialize.equals("")) { return initialize; } 
        krn.debugOut(this,0,krn.toString());
        krn.debugOut(this,0,MyCn.toString());
        pnl_TXN1.initialize(krn, cX);
        System.out.println("INNITICIS:" + sTyp_ciselnika + " ID:" + id_ciselnika);
        dbt_uni_cis1.set_uni_cis_Keys(sTyp_ciselnika,id_ciselnika);
        view_uni_cis1.setMetaDataEditor(xMetaDataEditor1);
        view_uni_cis1.set_uni_cis_Keys(sTyp_ciselnika,id_ciselnika);
        view_uni_cis1.initialize(krn,  cX);
        dbt_uni_cis1.initialize(krn, cX);
        view_uni_cis1.initialize(krn,  cX);
        krn.EOC_AddLink(this, dbt_uni_cis1,
                        view_uni_cis1, "row", "ENABLED");
        krn.EOC_AddLink((IEOC_Object) this, (IEOC_Object) pnl_TXN1,
                (IEOC_Object) view_uni_cis1, "update", "ENABLED");
         ////dBT_eas_usrgrp1.goToFirst("MUST");
        System.out.println("RUNNING_AFTERINNITTI");
        dbt_uni_cis1.afterInitialize();
        view_uni_cis1.afterInitialize();
        pnl_TXN1.afterInitialize();
        return "";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dbt_uni_cis1 = new system.tools.uni_cis.dbt_uni_cis();
        view_uni_cis1 = new system.tools.uni_cis.view_uni_cis();
        xMetaDataEditor1 = new eoc.xinterface.XMetaDataEditor();
        pnl_TXN1 = new eoc.widgets.Pnl_TXN();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dbt_uni_cis1, javax.swing.GroupLayout.DEFAULT_SIZE, 660, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(view_uni_cis1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(xMetaDataEditor1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
            .addComponent(pnl_TXN1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(dbt_uni_cis1, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(view_uni_cis1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(xMetaDataEditor1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(8, 8, 8)
                .addComponent(pnl_TXN1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private system.tools.uni_cis.dbt_uni_cis dbt_uni_cis1;
    private eoc.widgets.Pnl_TXN pnl_TXN1;
    private system.tools.uni_cis.view_uni_cis view_uni_cis1;
    private eoc.xinterface.XMetaDataEditor xMetaDataEditor1;
    // End of variables declaration//GEN-END:variables
}
