/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package easys.system.prog.uzivatelia;
import easys.system.prog.skupinyUzivatelov.Dlg_eas_usrgrp;
import eoc.*;
import eoc.database.DBconnection;
import system.Kernel;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import system.FnEaS;

/**
 *
 * @author rvanya
 */
public class Pnl_eas_users  extends eoc.widgets.PObject {
    private String choosedUsrGrpID; // posledny vyber skupiny metodou goToRow
    private String choosedUsersID; // 

    public Pnl_eas_users() {
       initComponents();
    }

   @Override
    public String initialize(Kernel kr, DBconnection cX) {

        String initialize = super.initialize(kr,  cX);
        if (!initialize.equals("")) { return initialize; } 

        krn.debugOut(this,0,krn.toString());
        krn.debugOut(this,0,MyCn.toString());
        eOC_Pnl_NAV1.initialize(krn, cX);
        eOC_Pnl_TXN1.initialize(krn, cX);
        dBT_eas_users1.initialize(krn, cX);
        dBT_eas_UserGrps1.initialize(krn, cX);
        view_eas_users1.initialize(krn, cX);
        krn.EOC_AddLink( this,  eOC_Pnl_NAV1, 
                         dBT_eas_users1 , "navigation", "ENABLED");
        krn.EOC_AddLink( this,  eOC_Pnl_TXN1, 
                         view_eas_users1, "update", "ENABLED");
        krn.EOC_AddLink( this,  dBT_eas_users1, 
                         dBT_eas_UserGrps1, "row", "ENABLED");
        krn.EOC_AddLink( this,  dBT_eas_users1, 
                         view_eas_users1, "row", "ENABLED");
        eOC_Pnl_NAV1.afterInitialize();
        eOC_Pnl_NAV1.afterInitialize();
        eOC_Pnl_TXN1.afterInitialize();
        eOC_Pnl_TXN1.afterInitialize();
        dBT_eas_users1.afterInitialize();
        dBT_eas_UserGrps1.afterInitialize();
        view_eas_users1.afterInitialize();
//                dBT_eas_users1.goToFirst("MUST");
//        dBT_eas_users1._evt_valueChanged();
        /*
        try {
            dBT_eas_UserGrps1.goToRow("");
        } catch (SQLException ex) {
            Logger.getLogger(Pnl_eas_users.class.getName()).log(Level.SEVERE, null, ex);
        }
        */
        return "";    
    }

    public String goToRow(String sMsg) {
        choosedUsrGrpID = FnEaS.sEntry(2, sMsg, "=");
        System.out.println(" KUUURVA- VZDIT TO FUNGUJEEE - goToRow: " + choosedUsrGrpID);
        return "";
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_users = new javax.swing.JPanel();
        dBT_eas_users1 = new easys.system.prog.uzivatelia.DBT_eas_users();
        jLabel1 = new javax.swing.JLabel();
        view_eas_users1 = new easys.system.prog.uzivatelia.View_eas_users();
        eOC_Pnl_TXN1 = new eoc.widgets.Pnl_TXN();
        eOC_Pnl_NAV1 = new eoc.widgets.Pnl_Navigation();
        jPanel_groups = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        dBT_eas_UserGrps1 = new easys.system.prog.uzivatelia.DBT_eas_UserGrps();
        jPanel_buttons = new javax.swing.JPanel();
        btn_Nova = new javax.swing.JButton();
        btn_Pridat = new javax.swing.JButton();
        btn_Odobrat = new javax.swing.JButton();

        jLabel1.setBackground(new java.awt.Color(179, 189, 223));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Užívatelia");
        jLabel1.setOpaque(true);

        javax.swing.GroupLayout jPanel_usersLayout = new javax.swing.GroupLayout(jPanel_users);
        jPanel_users.setLayout(jPanel_usersLayout);
        jPanel_usersLayout.setHorizontalGroup(
            jPanel_usersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_usersLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_usersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_usersLayout.createSequentialGroup()
                        .addComponent(eOC_Pnl_NAV1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(eOC_Pnl_TXN1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 74, Short.MAX_VALUE))
                    .addComponent(dBT_eas_users1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(view_eas_users1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel_usersLayout.setVerticalGroup(
            jPanel_usersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_usersLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dBT_eas_users1, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(view_eas_users1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_usersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(eOC_Pnl_TXN1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(eOC_Pnl_NAV1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel2.setBackground(new java.awt.Color(179, 189, 223));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 0, 204));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Skupiny, do ktorých užívateľ patrí");
        jLabel2.setOpaque(true);

        btn_Nova.setText("Nová");
        btn_Nova.setToolTipText("Pridanie skupiny z existujúcich skupín užívateľov, s možnosťou zadania novej skupiny");
        btn_Nova.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_NovaActionPerformed(evt);
            }
        });

        btn_Pridat.setText("Pridať");
        btn_Pridat.setToolTipText("Pridanie skupiny z existujúcich skupín užívateľov");
        btn_Pridat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PridatActionPerformed(evt);
            }
        });

        btn_Odobrat.setText("Odobrať");
        btn_Odobrat.setToolTipText("Odobratie už pridanej skupiny zo zoznamu pridelených skupín");
        btn_Odobrat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_OdobratActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_buttonsLayout = new javax.swing.GroupLayout(jPanel_buttons);
        jPanel_buttons.setLayout(jPanel_buttonsLayout);
        jPanel_buttonsLayout.setHorizontalGroup(
            jPanel_buttonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_buttonsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_Nova, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_Pridat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_Odobrat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel_buttonsLayout.setVerticalGroup(
            jPanel_buttonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_buttonsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_buttonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Nova)
                    .addComponent(btn_Pridat)
                    .addComponent(btn_Odobrat))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel_groupsLayout = new javax.swing.GroupLayout(jPanel_groups);
        jPanel_groups.setLayout(jPanel_groupsLayout);
        jPanel_groupsLayout.setHorizontalGroup(
            jPanel_groupsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_groupsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_groupsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dBT_eas_UserGrps1, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel_buttons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel_groupsLayout.setVerticalGroup(
            jPanel_groupsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_groupsLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dBT_eas_UserGrps1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel_buttons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jPanel_users, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_groups, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel_users, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel_groups, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_NovaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_NovaActionPerformed
         Dlg_eas_usrgrp dlg = new Dlg_eas_usrgrp(krn.getDsk().myJFrame,true, true  /* update-enabled */);
         dlg.initialize(krn, MyCn);
         dlg.createLinkTo(this, dlg, this, "row", "ENABLED");
         System.out.println("AAFFFTEEEERRR");
         String sVyber_RetVal;
         sVyber_RetVal = dlg.activate();
         choosedUsersID = dBT_eas_users1.getsCurrentMasterKeyValue();
         System.out.println("REETVAAAAL IS: " + sVyber_RetVal + " usersID == " + choosedUsersID + "  myObjectId:" + myObjectID.toString());
         if (sVyber_RetVal=="OK") {
             String succes = MyCn.getDbDriver().SQL_runStatement(MyCn.getConn(),"insert into eas_x_grpusr (id_eas_usrgrp, id_eas_users) values (" +
                             choosedUsrGrpID + "," + choosedUsersID + ")",true);
             if (succes.equals("")) {
                 dBT_eas_UserGrps1.refresh("");
                 EOC_message msg = new EOC_message(myObjectID,"refresh","blakiblakk", "");
                 krn.krn_sendMessage(myObjectID, msg, "row", "source");
////                 krn.krn_sendMessage(myObjectID, "refresh", "blakiblakk", "row", "SOURCE", null);
             }
             else {
                 krn.Message("E", succes, "Pridanie skupiny sa nepodarilo");
             }
         }
    }//GEN-LAST:event_btn_NovaActionPerformed

    private void btn_PridatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PridatActionPerformed
         Dlg_eas_usrgrp dlg = new Dlg_eas_usrgrp(krn.getDsk().myJFrame,true, false /* update-enabled */);
         dlg.initialize(krn, MyCn);
         dlg.createLinkTo(this, dlg, this, "row", "ENABLED");
         String sVyber_RetVal;
         sVyber_RetVal = dlg.activate();
         choosedUsersID = dBT_eas_users1.getsCurrentMasterKeyValue();
         if (sVyber_RetVal=="OK") {
////             String succes = krn.runStatement(MyCn,"insert into eas_x_grpusr (id_eas_usrgrp, id_eas_users) values (" +
////                             choosedUsrGrpID + "," + choosedUsersID + ")",true);
             String succes = krn.runInsertStatement(MyCn.getConn(),"eas_x_grpusr","id_eas_usrgrp^id_eas_users"
                                 ,choosedUsrGrpID + "^" + choosedUsersID,true,true,true);
             if (succes.equals("")) {
                 dBT_eas_UserGrps1.refresh("");
                 EOC_message msg = new EOC_message(myObjectID,"refresh","blakiblakk", "");
                 krn.krn_sendMessage(myObjectID, msg, "row", "source");
////                 krn.krn_sendMessage(myObjectID, "refresh", "blakiblakk", "row", "SOURCE", null);
             }
             else {
                 krn.Message("E", succes, "Pridanie skupiny sa nepodarilo");
             }
         }
    }//GEN-LAST:event_btn_PridatActionPerformed

    private void btn_OdobratActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_OdobratActionPerformed
       String skp = dBT_eas_UserGrps1.getColVal("c_group");
       if (skp != null) {
       if (krn.krnQuest("QN", "Odobrať skupinu " + skp + " ?", "Zrušenie členstva v skupine")) {
             String skpid = dBT_eas_UserGrps1.getColVal("id_eas_x_grpusr");
             String succes = MyCn.getDbDriver().SQL_runStatement(MyCn.getConn(),"delete from eas_x_grpusr where id_eas_x_grpusr =" + skpid, true);
             if (succes.equals("")) {
                 EOC_message msg = new EOC_message(myObjectID,"rowDeleted",skpid, "");
                 dBT_eas_UserGrps1.rowDeleted(msg);
                 //dBT_eas_UserGrps1.getTable().
                 dBT_eas_UserGrps1.refresh("");
             }
             else {
                 krn.Message ("E", succes, "Skupina sa nedá odstrániť.");
                 
             }
       } 
       }
       else {
           krn.Message("Nie je dostupná žiadna skupina na odobratie.");
       }
    }//GEN-LAST:event_btn_OdobratActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Nova;
    private javax.swing.JButton btn_Odobrat;
    private javax.swing.JButton btn_Pridat;
    private easys.system.prog.uzivatelia.DBT_eas_UserGrps dBT_eas_UserGrps1;
    private easys.system.prog.uzivatelia.DBT_eas_users dBT_eas_users1;
    private eoc.widgets.Pnl_Navigation eOC_Pnl_NAV1;
    private eoc.widgets.Pnl_TXN eOC_Pnl_TXN1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel_buttons;
    private javax.swing.JPanel jPanel_groups;
    private javax.swing.JPanel jPanel_users;
    private easys.system.prog.uzivatelia.View_eas_users view_eas_users1;
    // End of variables declaration//GEN-END:variables
}
