/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package easys.system.prog.uzivatelia;
import eoc.EOC_message;
import eoc.database.DBconnection;
import system.Kernel;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import java.awt.event.FocusListener;
import java.awt.event.FocusEvent;
import eoc.widgets.DTfield;
import java.awt.Component;
import java.awt.event.KeyEvent;


/**
 *
 * @author rvanya
 */
public class View_eas_users extends eoc.xinterface.XViewer implements eoc.IEOC_VisualObject {

   /**
    * Creates new form View_eas_users
    */
   public View_eas_users() {
      initComponents();
   }
    @Override
    public String initialize(Kernel kr, DBconnection cX) {
        super.initialize(kr,  cX);
        krn.debugOut(this,5,MyCn.toString());
        this.setMasterTable("eas.eas_users");
        this.setMasterKey("id_eas_users");//preco nenajde easusers ? je to v browseroch ?
        //toto vsetko sa da generovat aj zo SUPER
        String setQueryBase = this.setQueryBase ("select * from eas.eas_users");
        String setAppWhere = this.setAppWhere ("eas_users.id_eas_users=0");
        String rebuildQuery = this.rebuildQuery();
        String OpenQuery = this.OpenQuery();
          disableWidgets();
         return "";
   }

   /**
    * This method is called from within the constructor to initialize the form. WARNING:
    * Do NOT modify this code. The content of this method is always regenerated by the
    * Form Editor.
    */
   @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        eOC_DTfield2 = new eoc.widgets.DTfield();
        eOC_DTfield4 = new eoc.widgets.DTfield();
        eOC_DTfield3 = new eoc.widgets.DTfield();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                formFocusLost(evt);
            }
        });

        eOC_DTfield2.setText("c_user");
        eOC_DTfield2.setDbFieldLabel("Užívateľské meno");
        eOC_DTfield2.setDbFieldName("c_user");
        eOC_DTfield2.setDbTableName("eas.eas_users");
        eOC_DTfield2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eOC_DTfield2ActionPerformed(evt);
            }
        });

        eOC_DTfield4.setText("c_poznamka");
        eOC_DTfield4.setDbFieldLabel("Poznámky");
        eOC_DTfield4.setDbFieldName("c_poznamka");
        eOC_DTfield4.setDbTableName("eas.eas_users");
        eOC_DTfield4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eOC_DTfield4ActionPerformed(evt);
            }
        });

        eOC_DTfield3.setText("c_popis");
        eOC_DTfield3.setDbFieldLabel("Meno užívateľa");
        eOC_DTfield3.setDbFieldName("c_popis");
        eOC_DTfield3.setDbTableName("eas.eas_users");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Užívateľské meno:");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Celé meno užívateľa:");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Poznámky:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(eOC_DTfield2, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(eOC_DTfield4, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                    .addComponent(eOC_DTfield3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eOC_DTfield2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(eOC_DTfield3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eOC_DTfield4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

   private void eOC_DTfield2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eOC_DTfield2ActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_eOC_DTfield2ActionPerformed

   private void eOC_DTfield4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eOC_DTfield4ActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_eOC_DTfield4ActionPerformed

   private void formFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusLost
     System.out.println("formFocusLost");
     super.sformFocusLost(evt);
   }//GEN-LAST:event_formFocusLost

   private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
      System.out.println("formFocusGained");
      super.sformFocusGained(evt);
   }//GEN-LAST:event_formFocusGained

    @Override
    public String committxn(EOC_message eocMsg) {
        Integer iId = null;
        Integer iSkuCount = null;
        Integer iSId = null;
           /* priklad pouzitia v overridovanej funkcii
           alFieldValuePairs.clear();
           Object[] avl = new Object[2];
           avl[0] = "id_eas_grpusr";
           avl[1] = 4;
           alFieldValuePairs.add(avl);
           */
        if (sTxnType.equals("add") || sTxnType.equals("copy") ) {
            
           iId = (Integer) MyCn.getDbDriver().SQL_getQueryValue(MyCn.getConn(), 
                 "SELECT max(id_eas_users) as maxId from eas.eas_users", "maxId");
           if (iId==null) iId = 0; // ked este neexistuje ziadna veta
           iId++;

           super.committxn(eocMsg); //To change body of generated methods, choose Tools | Templates.
/* toto robi trigger v DB
           iSkuCount = (Integer) krn.getQueryValue(MyCn,
              "SELECT count(*) as cnt from eas.eas_x_grpusr where id_eas_users = " + iId, "cnt");
           if (iSkuCount == 0) {
               iSId = (Integer) krn.getQueryValue(MyCn, 
                 "SELECT id_eas_usrgrp as SId from eas.eas_usrgrp WHERE c_group  = '<bez_skupiny>'", "SId");
            alFieldValuePairs.clear();
            Object[] avl = new Object[2];
            avl[0] = "id_eas_users";
            avl[1] = iId;
            alFieldValuePairs.add(avl);
            if (!   
            krn.callSqlStatement(MyCn,"INSERT INTO eas.eas_x_grpusr (id_eas_usrgrp, id_eas_users) values (" +
                 iSId + "," + iId + ")"))
                return "UPDATE-ERROR (krn.callSqlStatement())";
           }
         */  
        }
        else {
            super.committxn(eocMsg); //To change body of generated methods, choose Tools | Templates.
        }
       return "";
    }

           
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private eoc.widgets.DTfield eOC_DTfield2;
    private eoc.widgets.DTfield eOC_DTfield3;
    private eoc.widgets.DTfield eOC_DTfield4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables

    @Override
    public String createLinkTo(Object oCreator, Object oVSrc, Object oVTrg, String sLink, String sState) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

}
