/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package easys.system.prog.skupinyUzivatelov;

import eoc.database.DBconnection;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;

/**
 *sQueryBase
 * @author rvanya
 */
public class DBT_eas_usrgrp extends eoc.xinterface.XTable {

    public DBT_eas_usrgrp() {
        initComponents();
    }
   @Override
   public String initialize(system.Kernel kr, DBconnection cX) {
      setMyObjectID(this);
      this.setConn(cX);
      this.setKrn(kr);
      
      this.setXTableType("DBTABLE");
      this.setMyTable(jTable1);
      this.setMyScrollPane(jScrollPane1);
      // Sybase
      //this.setMasterTable("osoby");
      //this.setMasterKey("id");
      //this.setMasterKeyDataType("INTEGER");
      //this.setDisplayedFields("id,meno,priez,rodmeno,dtnarod,rodcislo");
      //this.setQueryBase("select * from osoby");
       
      // Postgres
      this.setMasterTable("eas.eas_usrgrp");
      this.setMasterKey("id_eas_usrgrp","INTEGER");
      this.setDisplayedFields("c_group^Skupina^25,c_popis^Popis^50,c_poznamka^Poznámka^50");
      this.setQueryBase("select * from eas.eas_usrgrp");
      // this.setAppWhere("1=0"); // prazdne query
      // this.setAppWhere("id_eas_users < 50000");
     // this.setiNumFetchedRows(60);
      this.setiNumFetchedRows(-9999); // full fetch
      super.initialize(kr,cX);
      this.setTableEditable(false);
      return "";
   }

   public JTable getTable(){
      return jTable1;
   }   

    @Override
    public String afterInitialize() {
        super.afterInitialize(); //To change body of generated methods, choose Tools | Templates.
        closeQuery();
        open_Query();
        return "";
    }
   
//   public String fun_PolIDu(Integer rowIdx) {
   public Integer fun_PolIDu(Integer rowIdx) {
       //System.out.println("fun_PolIDu() -> Val = null .. begin ..");
      Object oVal = myTable.getValueAt(rowIdx, getTblColumnIndexBydbFieldName(myTable, "id_eas_usrgrp"));
      int iVal = Integer.parseInt(oVal.toString());
       return Integer.getInteger(String.valueOf(((double) iVal) / 2.8));
   /*
       System.out.println("fun_PolIDu() -> Val = " + iVal);
       return "3455";
       * */
   }

    @Override
    public String getCurrentObjPerms() {
       if (getCurrentRowStatus().equals("noRowAvailable")) return "N";

       if (this.getValueBydbFieldName("c_group").equals("<bez_skupiny>")) {
           return "NP";
       }
       else 
           return "NUCDP";
   } 
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(300, 64));

        jScrollPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(300, 64));

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTable1.setFillsViewportHeight(true);
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 492, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
