/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package easys.system.prog.skupinyUzivatelov;

import eoc.IEOC_Object;
import eoc.database.DBconnection;
import eoc.widgets.*;
import system.Kernel;
import system.FnEaS;
import java.awt.event.FocusListener;
import java.awt.event.WindowEvent;
import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;
import java.sql.Connection;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;

/**
 *
 * @author rvanya
 */
public class Dlg_eas_usrgrp extends DObject {

    private eoc.IEOC_VisualObject parentContainer; 
    public IEOC_Object myObjectID;
    public Kernel krn;
    public DBconnection MyCn;
    public boolean bInitialized;
    public JPanel myJPanel;
/*    
    private String usrPerms = ""; // "NOKT-V"
    private String objPerms = "NUDP";
    private String perms = "";
*/
    private int connectionStatus;
    private String sEOCobjectType = "<EOC_DObject_type_not_defined>";

    //    private Map<String, String> properties = new HashMap<String, String>();
    private Map<String, String> properties = new HashMap<>();
    private final Map<String, String> privateData = new HashMap<>();
    private String retVal = "<CANCELED>";
    /**
     * Creates new form EOC_DObject
     * @param parent
     * @param modal
     */
    public Dlg_eas_usrgrp(java.awt.Frame parent, boolean modal, boolean updEnabled) {
        super(parent, modal);
        initComponents();
        pnl_eas_usrgrp1.setUpdateEnabled(updEnabled);
        this.setEOC_objectType("EOC_DObject");
        setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);
    }

    
    /**
     * This method is called from within the constructor to initialize the form. WARNING:
     * Do NOT modify this code. The content of this method is always regenerated by the
     * Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_eas_usrgrp1 = new easys.system.prog.skupinyUzivatelov.Pnl_eas_usrgrp();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Výber + zadávanie skupín užívateľov");

        jButton1.setText("Vyber");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Zruš");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(60, 60, 60)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_eas_usrgrp1, javax.swing.GroupLayout.DEFAULT_SIZE, 575, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnl_eas_usrgrp1, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        retVal = "OK";
        this.processWindowEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        retVal = "<CANCELED>";
        this.processWindowEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DObject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DObject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DObject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DObject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                DObject dialog = new DObject(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    public String getProp(String key) {
        return properties.get(key);
    }

    public void setProp(String key, String value) {
        properties.put(key, value);
    }

    public void delProp(String key) {
        properties.remove(key);
    }

    /*
    @Override
    public void setObjPerms (String sPerms, boolean bTransmit) {
       objPerms = sPerms.toUpperCase();
       String lastPerms = perms;
       boolean bTransmit = disjoinPerms(sPerms);
       countPerms();
       if (!perms.equals(lastPerms) ) {
          krn.krn_sendMessage((Object) this,
                 "permissionChanged", joinPerms(bTransmit), "*","target", "");
       }
    }
    
    @Override
    public void setUsrPerms (String sPerms, boolean bTransmit) {
       usrPerms = sPerms.toUpperCase();
       String lastPerms = perms;
       boolean bTransmit = disjoinPerms(sPerms);
       countPerms();
       // udalost sa odosiela, len ked doslo k zmene hodnoty perms
       if (!perms.equals(lastPerms)) {
          krn.krn_sendMessage((Object) this,
                 "permissionChanged", joinPerms(bTransmit), "*","target", "");
       }
    }
*/    
    /*
    public String getUsrPerms() { return usrPerms;}

    public String getObjPerms() { return objPerms;}

    public String getPerms() { return perms;}
    
    public void countPerms() {
       perms = "";
       if (objPerms.contains("N") && usrPerms.contains("N")) {
          perms = perms + "N";
       }
       if (objPerms.contains("O") && usrPerms.contains("O")) {
          perms = perms + "O";
       }
       if (objPerms.contains("K") && usrPerms.contains("K")) {
          perms = perms + "K";
       }
       if (objPerms.contains("T") && usrPerms.contains("T")) {
          perms = perms + "T";
       }
       if (objPerms.contains("V") && usrPerms.contains("V")) {
          perms = perms + "V";
       }
    }
*/    
    @Override
    public String initialize(Kernel krnl, DBconnection cnX) {
        this.setKrn(krnl);
        this.setConn(cnX);
        pnl_eas_usrgrp1.initialize(krn, MyCn);
        bInitialized = true;
        return "";
    }
    @Override
    public String destroy() {
        /* sem by mal ist napriklad test na existenciu 
           necommitnutej transakcie, a osetrenie tohoto stavu */
        try {
            this.finalize();
        } catch (Throwable ex) {
            Logger.getLogger(eoc.IEOC_VisualObject.class.getName()).log(Level.SEVERE, null, ex);
        }
        return "";
    }

    @Override
    public DBconnection getConn() {
        return MyCn;
    }

    @Override
    public String sendMessage(eoc.EOC_message eocMessage, 
                              String sLinkType, String sVector) {
       return krn.krn_sendMessage(myObjectID, eocMessage, sLinkType, sVector);
    }

    // prijimac sprav od cudzich objektov
    @Override
    public String receiveMessage(eoc.EOC_message eocMsg) {

        // musi byt ako prva instrukcia v metode !!!
        if (eocMsg==null) return FnEaS.nullEocMessageResponse(myObjectID);
        
        // standardne hlasenie metody
       krn.debugOut(this,5,this.getClass().getName() + " EOC_VObject-Receiving message: "  
                         + eocMsg.getMessage() + " s parametrami: " + eocMsg.getParameters());
       //krn.krnMsg(this.getClass().getName() + " ** 1a PICABAAAA - EOC_VisualObject-Receiving message: "  
       //                  + sMessage + " s parametrami: " + sParameters);
       String rtVal = "NOTRECEIVED-in_VObject";
       try {
          // ziskanie vhodnej metody
          Method mtd;
          mtd = FnEaS.getEocMessageMethod(myObjectID, eocMsg);
         // krn.krnMsg(this.getClass().getName() + " ** 1b EOC_VisualObject-Receiving message: "  
         //                + sMessage + " s parametrami: " + sParameters + " mtd-is-null=" + (mtd==null));

          try {
             if (mtd != null) {
                if (!mtd.getReturnType().toString().equals("class java.lang.String")
                    && !mtd.getReturnType().equals(Void.TYPE)) {
                   krn.Message (this, "W", 
                              "Vrátená hodnota nie je typu 'String'", mtd.getName());
                }
                mtd.setAccessible(true);
                if (eocMsg.getParameters() == null) {
                   rtVal = (String) mtd.invoke(this);
                }
                else {
                   rtVal = (String) mtd.invoke(this, eocMsg.getParameters());
                }
                if (rtVal==null) {rtVal = ""; } // asi je metoda typu void
                return rtVal;
//krn.krnMsg(this.getClass().getName() + " ** 3a PICABAAAA - EOC_VisualObject-Receiving message: " + retVal);
       //krn.krnMsg(this.getClass().getName() + " ** 2a EOC_VisualObject-Receiving message: "  
           //              + sMessage + " s parametrami: " + sParameters + " RVL=" + retVal
           //     + " mtd-is-null=" + (mtd==null));
             }
/*
             // hladanie a spustenielokalnej verzie receiveMessage, pokial existuje
             mtd = FnEaS.getLocalReceiveMessageMethod(myObjectID);
         //krn.krnMsg(this.getClass().getName() + " ** 2b EOC_VisualObject-Receiving message: "  
         //                + sMessage + " s parametrami: " + sParameters + " RVL=" + retVal);
           if (mtd!=null) {
                 String locRetVal;
                 mtd.setAccessible(true);
                 locRetVal = (String) mtd.invoke(eocMsg.getSender(),eocMsg.getMessage(),eocMsg.getParameters(),eocMsg.getOthers());
                 if (locRetVal!=null) { retVal = retVal + locRetVal; }
             }
       krn.Message(this.getClass().getName() + " ** 3 EOC_VObject-Receiving message: "  
                         + eocMsg.getMessage() + " s parametrami: " + eocMsg.getParameters() + " RVL=" + retVal);
             return retVal;
 */            
          } catch (IllegalAccessException ex) {
             krn.debugOut(this,0,"VObject " + ex.toString());
             return "NOTRECEIVED-VObject=SUPER-IllegalAccessException=" + eocMsg.getMessage();
          } catch (IllegalArgumentException ex) {
             krn.debugOut(this,0,"VObject " + ex.toString());
             return "NOTRECEIVED-VObject=SUPER-IllegalArgumentException=" + eocMsg.getMessage();
          } catch (InvocationTargetException ex) {
             krn.debugOut(this,5,"VObject " + ex.toString()
                     + "\n>>>==== to je ON ====>>>" + ex.getTargetException());
             return "NOTRECEIVED-VObject=SUPER-InvocationTargetException=" + eocMsg.getMessage();
          }
       } catch (SecurityException ex) {
          return "NOTRECEIVED-VObject=SUPER-SecurityException=" + eocMsg.getMessage();
       }
       finally {
          // return "";
       }
       return rtVal;
    }

    @Override
    public String setConn(DBconnection cX) {
        this.MyCn = cX;
        return "";
     }

    @Override
    public String setKrn(Kernel krnl) {
         this.krn = krnl;
         return "";
    }

   
  /*     public void setMyTable(JPanel jFrm) {
        myJPanel = jFrm;
    }
*/

    @Override
    public void setMyObjectID(eoc.IEOC_Object evo) {
        myObjectID = evo;
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private easys.system.prog.skupinyUzivatelov.Pnl_eas_usrgrp pnl_eas_usrgrp1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void setConnectionStatus(int status) {
         connectionStatus = status;
    }

    @Override
    public String afterInitialize() {
        return "";
    }

    @Override
    public void setParentContainer(eoc.IEOC_VisualObject cntnr) {
            parentContainer = cntnr; 
    }

    @Override
    public boolean isContainer() {
        return true;
    }

    @Override
    public String CallMethod (Object oCaller, String sMethod, String sParameters) {
        return krn.CallMethod(oCaller,this,sMethod,sParameters);
    }

    public void setEOC_objectType(String sObjectType) {
        sEOCobjectType = sObjectType;
    }

    public String getEOC_objectType() {
      return "EOC_VObject";
   }

    @Override
    public Map<String, String> saveFrameToDef() {
        return krn.saveFrameToDef(this);
    }

    @Override
    public void restoreFrameFromDef(Object oPanel, Map<String, String> defMap) {
        krn.restorFrameFromDef(oPanel, defMap);
    }
    @Override
    public void setPrivateData(String key, String val) {
        privateData.put(key, val);
    }

    @Override
    public String getPrivateData(String key) {
        return privateData.get(key);
    }

    @Override
    public eoc.IEOC_VisualObject getParentContainer() {
        return parentContainer;
    }

    @Override
    public FocusListener getMyFocusListener() {
        FocusListener[] fl = this.getFocusListeners();
        return fl[0];
    }

    @Override
    public String createLinkTo(Object oCreator, Object oVSrc, Object oVTrg, String sLink, String sState) {

        sLink = sLink.toLowerCase(); // pre istotu
        if (sLink == "row") 
            pnl_eas_usrgrp1.createLinkTo(this, pnl_eas_usrgrp1, oVTrg, sLink, sState);
        return "";
    }

    public String activate() {
         pack();
         setLocationRelativeTo(krn.getDsk());
         setVisible(true);
         return retVal;
    }
}
