/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package easys.system.prog.skupinyUzivatelov;
import eoc.*;
import eoc.database.DBconnection;
import system.Kernel;
import java.sql.*;

/**
 *
 * @author rvanya
 */
public class Pnl_eas_usrgrp extends eoc.widgets.PObject {
    private boolean bUpdateEnabled = true;
    public Pnl_eas_usrgrp() {
       initComponents();
    }

    @Override
    public String initialize(Kernel kr, DBconnection cX) {
        setMyObjectID(this);
        String initialize = super.initialize(kr, cX);
        if (!initialize.equals("")) { return initialize; } 
        krn.debugOut(this,0,krn.toString());
        krn.debugOut(this,0,MyCn.toString());
        eOC_Pnl_NAV1.initialize(krn, cX);
        eOC_Pnl_TXN1.initialize(krn, cX);
        dBT_eas_usrgrp1.initialize(krn, cX);
        view_eas_usrgrp1.initialize(krn,  cX);
        krn.EOC_AddLink(this, dBT_eas_usrgrp1,
                 view_eas_usrgrp1, "row", "ENABLED");
        krn.EOC_AddLink((IEOC_Object) this, (IEOC_Object) eOC_Pnl_NAV1,
                 (IEOC_Object) dBT_eas_usrgrp1, "navigation", "ENABLED");
        krn.EOC_AddLink((IEOC_Object) this, (IEOC_Object) eOC_Pnl_TXN1,
                (IEOC_Object) view_eas_usrgrp1, "update", "ENABLED");
         dBT_eas_usrgrp1.goToFirst(new EOC_message(myObjectID,"goToFirst","MUST",""));
        eOC_Pnl_NAV1.afterInitialize();
        eOC_Pnl_TXN1.afterInitialize();
        dBT_eas_usrgrp1.afterInitialize();
        view_eas_usrgrp1.afterInitialize();
        return "";
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        eOC_Pnl_TXN1 = new eoc.widgets.Pnl_TXN();
        eOC_Pnl_NAV1 = new eoc.widgets.Pnl_Navigation();
        dBT_eas_usrgrp1 = new easys.system.prog.skupinyUzivatelov.DBT_eas_usrgrp();
        view_eas_usrgrp1 = new easys.system.prog.skupinyUzivatelov.View_eas_usrgrp();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dBT_eas_usrgrp1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(view_eas_usrgrp1, javax.swing.GroupLayout.DEFAULT_SIZE, 633, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(eOC_Pnl_NAV1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addComponent(eOC_Pnl_TXN1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dBT_eas_usrgrp1, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(view_eas_usrgrp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(eOC_Pnl_TXN1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eOC_Pnl_NAV1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private easys.system.prog.skupinyUzivatelov.DBT_eas_usrgrp dBT_eas_usrgrp1;
    private eoc.widgets.Pnl_Navigation eOC_Pnl_NAV1;
    private eoc.widgets.Pnl_TXN eOC_Pnl_TXN1;
    private easys.system.prog.skupinyUzivatelov.View_eas_usrgrp view_eas_usrgrp1;
    // End of variables declaration//GEN-END:variables

    @Override
    public String destroy() {
        //throw new UnsupportedOperationException("Not supported yet.");
        return "";
    }

    @Override
    public String createLinkTo(Object oCreator, Object oVSrc, Object oVTrg, String sLink, String sState) {
        sLink = sLink.toLowerCase(); // pre istotu
        if (sLink == "row") 
            krn.EOC_AddLink(this, dBT_eas_usrgrp1, oVTrg, "row", "ENABLED");
        return "";
        
    }

    public void setUpdateEnabled(boolean updEnab) {
        bUpdateEnabled = updEnab;
        eOC_Pnl_TXN1.setVisible(updEnab);
    }
    
    
}
