/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package easys.system.prog.skupinyUzivatelov;
import eoc.EOC_message;
import eoc.FocusGrabber;
import eoc.database.DBconnection;
import system.Kernel;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.text.DefaultFormatter;
/**
 *
 * @author rvanya
 */
public class View_eas_usrgrp extends eoc.xinterface.XViewer {

    /**
     * Creates new form View_eas_usrgrp
     */
    public View_eas_usrgrp() {
        initComponents();
    }
    @Override
    public String initialize(Kernel kr, DBconnection cX) {
        super.initialize(kr, cX);
        krn.debugOut(this,5,MyCn.toString());
        this.setMasterTable("eas.eas_usrgrp");
        //toto vsetko sa da generovat aj zo SUPER
        String setQueryBase = this.setQueryBase ("select * from eas.eas_usrgrp");
        String setAppWhere = this.setAppWhere ("eas_usrgrp.id_eas_usrgrp=0");
        setMasterKey("id_eas_usrgrp");
        String rebuildQuery = this.rebuildQuery();
        String OpenQuery = this.OpenQuery();
        disableWidgets();
        return "";
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        dTfield2 = new eoc.widgets.DTfield();
        dTfield3 = new eoc.widgets.DTfield();
        dTfield4 = new eoc.widgets.DTfield();

        jButton1.setText("jButton1");

        setBorder(new javax.swing.border.MatteBorder(null));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setLabelFor(dTfield4);
        jLabel1.setText("Skupina:");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setLabelFor(dTfield2);
        jLabel2.setText("Popis:");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setLabelFor(dTfield3);
        jLabel4.setText("Poznámka:");

        jButton2.setText("Dialog test");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        dTfield2.setText("c_popis");
        dTfield2.setDbFieldName("c_popis");
        dTfield2.setDbTableName("eas.eas_usrgrp");
        dTfield2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dTfield2ActionPerformed(evt);
            }
        });
        dTfield2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                dTfield2KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                dTfield2KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                dTfield2KeyTyped(evt);
            }
        });

        dTfield3.setText("c_poznamka");
        dTfield3.setDbFieldName("c_poznamka");
        dTfield3.setDbTableName("eas.eas_usrgrp");

        dTfield4.setText("c_group");
        dTfield4.setDbFieldName("c_group");
        dTfield4.setDbOnLeave("c_group_onLeave");
        dTfield4.setDbTableName("eas.eas_usrgrp");
        dTfield4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                dTfield4FocusLost(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(dTfield4, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(dTfield2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dTfield3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(dTfield4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dTfield2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dTfield3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );
    }// </editor-fold>//GEN-END:initComponents

   private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
   //krn.krnMsg("Ešte nefunguje. :-)");          
  if (krn.krnQuest("WY", "No co odpovies na prvu otazku ?", "Pokusny dialog"))
  {krn.Message("OK");} else {krn.Message("Odmietol si to, ti suflikant");}
   }//GEN-LAST:event_jButton2ActionPerformed

    private void dTfield4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dTfield4FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_dTfield4FocusLost

    private void dTfield2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dTfield2KeyPressed
        if (evt.getKeyChar()=='f') {
            DefaultFormatter dfmt = (DefaultFormatter) dTfield2.getFormatter();
            ////System.out.println("pOVERWRITEMODE==" + dfmt.getOverwriteMode());
        }
    }//GEN-LAST:event_dTfield2KeyPressed

    private void dTfield2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dTfield2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dTfield2ActionPerformed

    private void dTfield2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dTfield2KeyReleased
        if (evt.getKeyChar()=='f') {
            DefaultFormatter dfmt = (DefaultFormatter) dTfield2.getFormatter();
            ////System.out.println("rOVERWRITEMODE==" + dfmt.getOverwriteMode());
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_dTfield2KeyReleased

    private void dTfield2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dTfield2KeyTyped
        if (evt.getKeyChar()=='f') {
            DefaultFormatter dfmt = (DefaultFormatter) dTfield2.getFormatter();
            ////System.out.println("tOVERWRITEMODE==" + dfmt.getOverwriteMode());
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_dTfield2KeyTyped
private void flost(java.awt.event.FocusEvent evt) {
        //krn.krnMsg("E", "blabla", null);
        //SwingUtilities.invokeLater(new FocusGrabber(this));
        //evt.getComponent().requestFocus();
        //evt. .consume();
}
    @Override
    public String aftercommit(EOC_message eocMsg) {
        System.out.println("HURRAA-local__aftercommit");
        super.aftercommit(eocMsg);
        return "";
    }
    
    public boolean c_group_onLeave() {
        // test existencie hodnoty v DB
        // if ()
        return true;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private eoc.widgets.DTfield dTfield2;
    private eoc.widgets.DTfield dTfield3;
    private eoc.widgets.DTfield dTfield4;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables


}
