/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package system.desktop;

import java.awt.Color;
import java.awt.LayoutManager;
import javax.swing.JButton;
import javax.swing.JTextField;
import system.Kernel;

/**
 *
 * @author rvanya
 */
public class Pnl_modules extends eoc.widgets.PObject {
   JTextField tx = new JTextField();
   /**
    * Creates new form EOC_Pnl_modules
    */
   public Pnl_modules() {
      initComponents();
   }
   
   
   /**
    * This method is called from within the constructor to initialize the form. WARNING:
    * Do NOT modify this code. The content of this method is always regenerated by the
    * Form Editor.
    */
   @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_CloseActiveModul = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(32767, 23));
        setMinimumSize(new java.awt.Dimension(165, 23));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        btn_CloseActiveModul.setIcon(new javax.swing.ImageIcon(getClass().getResource("/easys/res/img/Koniec.png"))); // NOI18N
        btn_CloseActiveModul.setToolTipText("Ukončenie behu systému");
        btn_CloseActiveModul.setFocusable(false);
        btn_CloseActiveModul.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_CloseActiveModul.setIconTextGap(0);
        btn_CloseActiveModul.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btn_CloseActiveModul.setMaximumSize(new java.awt.Dimension(25, 25));
        btn_CloseActiveModul.setMinimumSize(new java.awt.Dimension(25, 25));
        btn_CloseActiveModul.setPreferredSize(new java.awt.Dimension(25, 25));
        btn_CloseActiveModul.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_CloseActiveModul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CloseActiveModulActionPerformed(evt);
            }
        });
        add(btn_CloseActiveModul);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_CloseActiveModulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CloseActiveModulActionPerformed
        // sem pridu opatrenia ci sa moze/nemoze vypnut modul
        // v krn treba spravit nieco co ten modul potom zmeni na dis
        //        removeModulPane(); - Attila
        Kernel.staticMsg("<html>Funkcia zatial nie je implementovaná.<BR><BR>" 
                       + "Na ukončenie tam máš <B>[X]</B>-kové tlačítko.<BR><BR>" 
                       + "(v pravom hornom rohu okna.)<BR><BR>(aspoň vo <B>Windofsochh</B>.)&nbsp&nbsp&nbsp&nbsp<B>:o)</B>"
                       + "</html>");
        return;
        // mohloby to bit nieco ako:
        // krn.exit(0);
        // System.exit(0);
    }//GEN-LAST:event_btn_CloseActiveModulActionPerformed

   public void addButton(JButton btn) {
     btn.setSize(50,25);
      this.add(btn);
      LayoutManager layout = this.getLayout();
      /*
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(btn_CloseActiveModul, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
         .addGroup(layout.createSequentialGroup()
            .addComponent(jButton1)
            .addGap(0, 0, Short.MAX_VALUE))
*/
      this.invalidate();
      layout.addLayoutComponent(btn.getText(), btn);
      this.doLayout();
      btn.setVisible(true);
   }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_CloseActiveModul;
    // End of variables declaration//GEN-END:variables
}
