/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package eoc.calendar;
import eoc.database.DBconnection;
import system.Kernel;
import java.sql.*;
import system.FnEaS;

/**
 *
 * @author rvanya
 */
public class Pnl_calendarContainer  extends eoc.widgets.PObject {
    private String choosedUsrGrpID; // posledny vyber skupiny metodou goToRow
    public Pnl_calendarContainer() {
       initComponents();
    }
public boolean freezeForOwner(String sOwner) {
    return pnl_owner_source1.freezeForOwner(sOwner);
}
    
   @Override
    public String initialize(Kernel kr, DBconnection cX) {

        String initialize = super.initialize(kr,  cX);
        if (!initialize.equals("")) { return initialize; } 

        krn.debugOut(this,0,krn.toString());
        krn.debugOut(this,0,MyCn.toString());
        pnl_owner_source1.initialize(krn, cX);
        pnl_navigation_source1.initialize(krn, cX);
        pnl_calendarTableGroup1.initialize(krn, cX);
        pnl_owner_source1.load_all_accounts(true);
        
        krn.EOC_AddLink( this, pnl_owner_source1, 
                         pnl_calendarTableGroup1 , "calendarOwner", "ENABLED");
// ASI NEFUNGUJE, KED SU V DVOCH LINKOCH TIE ISTE OBJEKTY !!!!       krn.EOC_AddLink( this, pnl_navigation_source1, 
//                         pnl_calendarTableGroup1 , "lookManager", "ENABLED");
        krn.EOC_AddLink( this, pnl_navigation_source1, 
                         pnl_calendarTableGroup1 , "navigation", "ENABLED");
        
        pnl_owner_source1.afterInitialize();
        pnl_navigation_source1.afterInitialize();
        pnl_calendarTableGroup1.afterInitialize();
        return "";    
    }

    public String goToRow(String sMsg) {
        choosedUsrGrpID = FnEaS.sEntry(2, sMsg, "=");
        System.out.println(" KUUURVA- VZDIT TO FUNGUJEEE - goToRow: " + choosedUsrGrpID);
        return "";
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_users = new javax.swing.JPanel();
        pnl_owner_source1 = new eoc.calendar.Pnl_owner_source();
        pnl_calendarTableGroup1 = new eoc.calendar.Pnl_calendarTableGroup();
        pnl_navigation_source1 = new eoc.calendar.Pnl_navigation_source();

        javax.swing.GroupLayout jPanel_usersLayout = new javax.swing.GroupLayout(jPanel_users);
        jPanel_users.setLayout(jPanel_usersLayout);
        jPanel_usersLayout.setHorizontalGroup(
            jPanel_usersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_usersLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_usersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_usersLayout.createSequentialGroup()
                        .addComponent(pnl_owner_source1, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnl_navigation_source1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE))
                    .addComponent(pnl_calendarTableGroup1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1019, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel_usersLayout.setVerticalGroup(
            jPanel_usersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_usersLayout.createSequentialGroup()
                .addGroup(jPanel_usersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnl_navigation_source1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl_owner_source1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnl_calendarTableGroup1, javax.swing.GroupLayout.DEFAULT_SIZE, 541, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jPanel_users, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel_users, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel_users;
    private eoc.calendar.Pnl_calendarTableGroup pnl_calendarTableGroup1;
    private eoc.calendar.Pnl_navigation_source pnl_navigation_source1;
    private eoc.calendar.Pnl_owner_source pnl_owner_source1;
    // End of variables declaration//GEN-END:variables
}
