/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package eoc.calendar;

import eoc.database.DBconnection;
import eoc.xinterface.XTable;
import java.sql.Connection;
import system.Kernel;

/**
 *
 * @author rvanya
 */
public class View_event_updater extends eoc.xinterface.XViewer {
    /**
     * Creates new form view_navstevy
     */
    public View_event_updater() {
        initComponents();
    }
    
    @Override
    public String initialize(Kernel kr, DBconnection cX) {
        if (bInitialized) return "";
        krn = kr;
        MyCn = cX;
        this.setMasterTable("nzbd.nz_vr_hlas_zavad");
        //toto vsetko sa da generovat aj zo SUPER
        String setQueryBase = this.setQueryBase ("select * from nzbd.nz_vr_hlas_zavad");
        String setAppWhere = this.setAppWhere ("nz_vr_hlas_zavad.id_nz_vr_hlas_zavad=0");
        setMasterKey("id_nz_vr_hlas_zavad");
        super.initialize(kr, cX);
        ////showFormatter("1");
        String rebuildQuery = this.rebuildQuery();
        String OpenQuery = this.OpenQuery();
        System.out.println("disabling 1");
        disableWidgets();
        System.out.println("disabling 2");
        ////showFormatter("2");
        bInitialized = true; 
        this.revalidate();
        return "";
   }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        dta_c_pozn_udrzbara = new eoc.widgets.DTtextArea();
        jLabel5 = new javax.swing.JLabel();
        dTcb_c_popis_zavady = new eoc.widgets.DTcomboBox();
        jLabel11 = new javax.swing.JLabel();
        dtf_c_popis_zavady = new eoc.widgets.DTfield();
        jLabel12 = new javax.swing.JLabel();
        dTcb_c_subj_zavady = new eoc.widgets.DTcomboBox();
        jLabel13 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        d_dtf_d_den_hlasenia = new eoc.widgets.DTfield();
        jLabel8 = new javax.swing.JLabel();
        dtf_c_cas_od = new eoc.widgets.DTfield();
        jLabel1 = new javax.swing.JLabel();
        dtf_i_PorCisZaDen = new eoc.widgets.DTfield();
        d_dtf_d_den_hlasenia1 = new eoc.widgets.DTfield();
        jLabel14 = new javax.swing.JLabel();
        dtf_c_cas_do = new eoc.widgets.DTfield();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        dTcomboBox1 = new eoc.widgets.DTcomboBox();
        jLabel10 = new javax.swing.JLabel();
        dTXfield1 = new eoc.widgets.DTXfield();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        dtf_c_navstiveny = new eoc.widgets.DTfield();
        jLabel7 = new javax.swing.JLabel();
        dtf_c_meno = new eoc.widgets.DTfield();
        dTX_c_subj_zavady = new eoc.widgets.DTXfield();

        dta_c_pozn_udrzbara.setColumns(20);
        dta_c_pozn_udrzbara.setRows(5);
        dta_c_pozn_udrzbara.setText("c_poznamky");
        dta_c_pozn_udrzbara.setDbFieldName("c_pozn_udrzbara");
        dta_c_pozn_udrzbara.setDbTableName("nz_vr_hlas_zavad");
        jScrollPane1.setViewportView(dta_c_pozn_udrzbara);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Poznámky");

        dTcb_c_popis_zavady.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Plyn", "Voda", "Vytah", "Iny" }));
        dTcb_c_popis_zavady.setDbFieldName("c_typ_zavady");
        dTcb_c_popis_zavady.setdbScreenValueDefinition("<Not Set>");
        dTcb_c_popis_zavady.setDbTableName("nz_vr_hlas_zavad");
        dTcb_c_popis_zavady.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dTcb_c_popis_zavadyActionPerformed(evt);
            }
        });

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Typ závady:");

        dtf_c_popis_zavady.setText("c_popis_zavady");
        dtf_c_popis_zavady.setDbFieldName("c_popis_zavady");
        dtf_c_popis_zavady.setDbTableName("nz_vr_hlas_zavad");
        dtf_c_popis_zavady.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dtf_c_popis_zavadyActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setText("Popis závady:");

        dTcb_c_subj_zavady.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Dom", "Vchod", "Byt" }));
        dTcb_c_subj_zavady.setDbFieldName("c_subj_zavady");
        dTcb_c_subj_zavady.setdbScreenValueDefinition("<Not Set>");
        dTcb_c_subj_zavady.setDbTableName("nz_vr_hlas_zavad");
        dTcb_c_subj_zavady.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dTcb_c_subj_zavadyActionPerformed(evt);
            }
        });

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("Miesto závady:");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Deň nahlásenia:");

        d_dtf_d_den_hlasenia.setText("d_den_hlasenia");
        d_dtf_d_den_hlasenia.setDbFieldName("d_den_hlasenia");
        d_dtf_d_den_hlasenia.setDbTableName("nz_vr_hlas_zavad");
        d_dtf_d_den_hlasenia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d_dtf_d_den_hlaseniaActionPerformed(evt);
            }
        });

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Čas hlásenia:");

        dtf_c_cas_od.setText("c_cas_hlasenia");
        dtf_c_cas_od.setDbFieldLabel("");
        dtf_c_cas_od.setDbFieldName("c_cas_hlasenia");
        dtf_c_cas_od.setDbFormatString("$TIME");
        dtf_c_cas_od.setDbTableName("nz_vr_hlas_zavad");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Zapísal:");

        dtf_i_PorCisZaDen.setDbEnableWhen("-");
        dtf_i_PorCisZaDen.setDbFieldName("c_zapisal");
        dtf_i_PorCisZaDen.setDbGroupList("");
        dtf_i_PorCisZaDen.setDbTableName("nz_vr_hlas_zavad");
        dtf_i_PorCisZaDen.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("# ### ###"))));
        dtf_i_PorCisZaDen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dtf_i_PorCisZaDenActionPerformed(evt);
            }
        });

        d_dtf_d_den_hlasenia1.setText("d_den_vyriesenia");
        d_dtf_d_den_hlasenia1.setDbFieldName("d_den_vyriesenia");
        d_dtf_d_den_hlasenia1.setDbTableName("nz_vr_hlas_zavad");
        d_dtf_d_den_hlasenia1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d_dtf_d_den_hlasenia1ActionPerformed(evt);
            }
        });

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("Deň odstránenia:");

        dtf_c_cas_do.setText("c_cas_vyriesenia");
        dtf_c_cas_do.setDbFieldLabel("");
        dtf_c_cas_do.setDbFieldName("c_cas_vyriesenia");
        dtf_c_cas_do.setDbFormatString("$TIME");
        dtf_c_cas_do.setDbTableName("nz_vr_hlas_zavad");
        dtf_c_cas_do.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dtf_c_cas_doActionPerformed(evt);
            }
        });

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel15.setText("Čas odstránenia:");

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel16.setText("Odstránil:");

        dTcomboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Neriešená", "Hlásená opravárovi", "Rieši sa to", "Odstránená" }));
        dTcomboBox1.setDbFieldName("c_stav_riesenia");
        dTcomboBox1.setdbScreenValueDefinition("<Not Set>");
        dTcomboBox1.setDbTableName("nz_vr_hlas_zavad");
        dTcomboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dTcomboBox1ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("Stav riešenia");

        dTXfield1.setText("c_udrzbar");
        dTXfield1.setdbChooseDefinition("#PRAC#ID#CISLO^Os.číslo,MENOPR^Meno,PRIEZPR^Priezvisko#CISLO,PRIEZPR,MENOPR,ID#Výber opravárov#ubf = 1 and visible = 1#PRIEZPR#Výber údržbárov ");
        dTXfield1.setDbFieldName("c_udrzbar");
        dTXfield1.setdbScreenValueDefinition("FUN@getUdrzbar");
        dTXfield1.setDbTableName("nz_vr_hlas_zavad");
        dTXfield1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dTXfield1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(d_dtf_d_den_hlasenia, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(d_dtf_d_den_hlasenia1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(dtf_c_cas_od, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(dtf_c_cas_do, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dtf_i_PorCisZaDen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dTXfield1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dTcomboBox1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(d_dtf_d_den_hlasenia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dtf_i_PorCisZaDen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(dtf_c_cas_od, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(d_dtf_d_den_hlasenia1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(dtf_c_cas_do, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(dTcomboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dTXfield1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Nahlásil:");

        dtf_c_navstiveny.setText("c_nahlasil");
        dtf_c_navstiveny.setDbFieldName("c_nahlasil");
        dtf_c_navstiveny.setDbTableName("nz_vr_hlas_zavad");
        dtf_c_navstiveny.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dtf_c_navstivenyActionPerformed(evt);
            }
        });

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Kontakt/tel.číslo:");

        dtf_c_meno.setText("c_kontakt");
        dtf_c_meno.setDbFieldName("c_kontakt");
        dtf_c_meno.setDbTableName("nz_vr_hlas_zavad");
        dtf_c_meno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dtf_c_menoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dtf_c_navstiveny, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(33, 33, 33)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dtf_c_meno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(dtf_c_navstiveny, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(dtf_c_meno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        dTX_c_subj_zavady.setText("c_subj_zavady");
        dTX_c_subj_zavady.setdbChooseDefinition("#BYT#ID#KMC^Var. symbol, FUN@getUlica^Ulica^string^30#KMC,FUN@getUlica,VCH_ID#Výber bytov##KMC#Výber bytu, kde sa má oprava vykonať ");
        dTX_c_subj_zavady.setDbFieldLabel("");
        dTX_c_subj_zavady.setDbFieldName("id_subj_zavady");
        dTX_c_subj_zavady.setdbScreenValueDefinition("FUN@getUlica");
        dTX_c_subj_zavady.setDbTableName("nz_vr_hlas_zavad");
        dTX_c_subj_zavady.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dTX_c_subj_zavadyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 805, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(dTcb_c_subj_zavady, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                                    .addComponent(dTcb_c_popis_zavady, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dtf_c_popis_zavady, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(dTX_c_subj_zavady, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(11, 11, 11))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(dTcb_c_popis_zavady, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dtf_c_popis_zavady, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(dTcb_c_subj_zavady, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dTX_c_subj_zavady, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void dtf_c_menoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dtf_c_menoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dtf_c_menoActionPerformed

    private void dtf_c_navstivenyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dtf_c_navstivenyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dtf_c_navstivenyActionPerformed

    private void d_dtf_d_den_hlaseniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_d_dtf_d_den_hlaseniaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_d_dtf_d_den_hlaseniaActionPerformed

    private void dtf_i_PorCisZaDenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dtf_i_PorCisZaDenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dtf_i_PorCisZaDenActionPerformed

    private void dtf_c_cas_doActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dtf_c_cas_doActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dtf_c_cas_doActionPerformed

    private void dTcb_c_popis_zavadyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dTcb_c_popis_zavadyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dTcb_c_popis_zavadyActionPerformed

    private void dtf_c_popis_zavadyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dtf_c_popis_zavadyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dtf_c_popis_zavadyActionPerformed

    private void dTcb_c_subj_zavadyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dTcb_c_subj_zavadyActionPerformed

        String s = dTcb_c_subj_zavady.getSelectedItem().toString();

////        System.out.println("SITTEM: " + s);
        if (s.equalsIgnoreCase("Dom")) 
            dTX_c_subj_zavady.setdbChooseDefinition(
"#VCS#ID#VCS^Č.VCS,ULICA^Ulica^string^70#VCS,ULICA,ID#Výber VČS##VCS#Výber domu, kde sa má oprava vykonať"
            );
        else if (s.equalsIgnoreCase("Vchod")) 
            dTX_c_subj_zavady.setdbChooseDefinition(
"#VCHOD#ID#VCHOD^+C. vchodu,ULICA^Vchod^string^70#VCHOD,ULICA,ID#Výber vchodov##VCHOD#Výber vchodu, kde sa má oprava vykonať"
            );
        else if (s.equalsIgnoreCase("Byt"))
            dTX_c_subj_zavady.setdbChooseDefinition(
"#BYT#ID#KMC^Var. symbol, FUN@getByt^Byt^string^180#KMC,FUN@getByt,VCH_ID#Výber bytov##KMC#Výber bytu, kde sa má oprava vykonať"
            );
            ;
    }//GEN-LAST:event_dTcb_c_subj_zavadyActionPerformed

    private void d_dtf_d_den_hlasenia1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_d_dtf_d_den_hlasenia1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_d_dtf_d_den_hlasenia1ActionPerformed

    private void dTcomboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dTcomboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dTcomboBox1ActionPerformed

    private void dTX_c_subj_zavadyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dTX_c_subj_zavadyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dTX_c_subj_zavadyActionPerformed

    private void dTXfield1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dTXfield1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dTXfield1ActionPerformed

    @Override
    public String clearWidgets() {
////        showFormatter("3aclearWidgets");
        String s = super.clearWidgets(); //To change body of generated methods, choose Tools | Templates.
////        showFormatter("3bclearWidgets");
        return s;
        
    }

    @Override
    public String disableWidgets() {
////        showFormatter("4adisableWidgets");
        String s = super.disableWidgets(); //To change body of generated methods, choose Tools | Templates.
////                                krn.krnMsg("nu a tutok ?? asko totovyzseraa?");

////        showFormatter("4bdisableWidgets");
        return s;
    }

    @Override
    public String afterInitialize() {
////        showFormatter("5aafterInitialize");
        String s = super.afterInitialize(); //To change body of generated methods, choose Tools | Templates.
        super.refreshFormatters(); //To change body of generated methods, choose Tools | Templates.
////        showFormatter("5bafterInitialize");
        return s;
}
    
    public void showFormatterClass(String flag) {
        System.out.println(flag + " -----dTfield5formatterclass: " + dtf_c_cas_od.getFormatter().getClass()
        + "  dbFormatString==" + dtf_c_cas_od.getDbFormatString());
    }
    
    public String getUlica (Object subjid) {
        String subj = dTcb_c_subj_zavady.getSelectedItem().toString();
////        System.out.println("getttingUlica for object:" + subjid.toString() + " subjekt:" + subj);
        String rtv;
        if (subj.startsWith("D")) rtv = getDom(subjid);
        else if (subj.startsWith("V")) rtv = getVchod(subjid);
        else if (subj.startsWith("B")) rtv = getByt(subjid);
        else rtv = "Neznámy typ subjektu:" + subj;
        return rtv;
    }

    public String getUlica (String subj, Integer subjid) {
        String rtv;
        if (subj.startsWith("D")) rtv = getDom(subjid);
        else if (subj.startsWith("V")) rtv = getVchod(subjid);
        else if (subj.startsWith("B")) rtv = getByt(subjid);
        else rtv = "Neznámy typ subjektu:" + subj;
        return rtv;
    }

    public String getUlica (XTable xtb, Integer rowNum) {
        String s = xtb.getValueBydbFieldName(rowNum,"c_subj_zavady").toString(); 
        Object o = xtb.getValueBydbFieldName(rowNum,"id_subj_zavady");
        String rtv;
        if (s.startsWith("D")) rtv = getDom(o);
        else if (s.startsWith("V")) rtv = getVchod(o);
        else if (s.startsWith("B")) rtv = getByt(o);
        else rtv = "Neznámy typ subjektu:" + s;
        return rtv;
    }

    public String getDom (Object s) {
        if (s==null || s.toString().equals("")) return "";
        Integer iSubj_ID;
        try {
            iSubj_ID = Integer.parseInt(s.toString());
        }
        catch (NumberFormatException ex) {
////            System.out.println(">>NUMFORMEXCPT");
            return "NUMFORMAT-EXCEPTION";
        }
        String gry = "SELECT VCS + ' - ' + ULICA as retval FROM VCS"
                + " WHERE id = " + iSubj_ID;
////        System.out.println("getttDom for id:" + s.toString());
        Object rtv = MyCn.getDbDriver().SQL_getQueryAsValue(MyCn.getConn(), gry, true);
        return rtv.toString();
    }
    
    public String getVchod (Object s) {
        if (s==null || s.toString().equals("")) return "";
        Integer iSubj_ID;
        try {
            iSubj_ID = Integer.parseInt(s.toString());
        }
        catch (NumberFormatException ex) {
            System.out.println(">>NUMFORMEXCPT");
            return "NUMFORMAT-EXCEPTION";
        }
        String gry = "SELECT VCHOD + ' - ' + ULICA as retval FROM VCHOD"
                + " WHERE id = " + iSubj_ID;
////        System.out.println("getttVchod for id:" + iSubj_ID);
        Object rtv = MyCn.getDbDriver().SQL_getQueryAsValue(MyCn.getConn(), gry, true);
        return rtv.toString();
    }
    
    public String getByt (Object s) {
        String gry = 
        "SELECT BYT.KMC + ' - ' + DOM.ULICA + ' - ' + DOM.MESTO + ' - ' +" +
        "(SELECT OSOBY.PRIEZ + ' ' + OSOBY.MENO FROM UZIVATELIA JOIN OSOBY WHERE UZIVATELIA.ID = " + 
        "(SELECT max(ID) FROM UZIVATELIA WHERE UZIVATELIA.BYT_ID = BYT.ID AND DTODST = " + 
        "(SELECT max(DTODST) FROM UZIVATELIA WHERE UZIVATELIA.BYT_ID = BYT.ID))) AS retVal " +
        "FROM BYT JOIN VCHOD JOIN VCS JOIN DOM ON DOM.ID = VCHOD.DOM_ID " +
        "WHERE BYT.ID = "  + s.toString() + ""; 
////        System.out.println("getttByt for id:" + s.toString());
        Object rtv = MyCn.getDbDriver().SQL_getQueryAsValue(MyCn.getConn(), gry, true);
        return rtv.toString();
    }
    
    public String getByt (XTable xtb, Integer rowNum) {
        // ziskanie identifikatora bytu
        Object s = xtb.getValueBydbFieldName(rowNum,"ID"); 
        // vratenie popisu bytu
        return getByt(s);
    }

    public String getUdrzbar (Object o) {
        if (o.toString().equals("")) return ""; 
        String rv = null;
        try {
            Integer i = Integer.parseInt(o.toString()); // id tabulky VCHOD
            rv = getUdrzbar(i);
        }
        catch (Exception ex) {
            rv = "ERR_getUdrzbar(o)_" + o.toString();
        }
        return rv;
        //return "U-u-ulica basmekk_obj";
    }
    public String getUdrzbar (XTable xtb, Integer rowNum) {
////         System.out.println("XTB_UDRZBAAARID ON ROW===" + rowNum);
        Object o = xtb.getValueBydbFieldName(rowNum,"c_udrzbar");
        if (o.toString().equals("")) return ""; 
        Integer iPcislo;
        try {
            iPcislo = Integer.parseInt(o.toString());
        }
        catch (NumberFormatException ex) {
            System.out.println(">>NUMFORMEXCPT");
            iPcislo = null;
        }
        if (iPcislo == null) return "ERR_getUdrzbar(xtb,iRowNum)" + o.toString();
        String gry = "SELECT PRIEZPR + ' ' + MENOPR as retval FROM PRAC WHERE ID = " + iPcislo + "";
        Object rtv = MyCn.getDbDriver().SQL_getQueryAsValue(MyCn.getConn(), gry, true);
        return rtv.toString();
    }
    public String getUdrzbar (Integer pracId) {
////        System.out.println("INT_UDRZBAAARID===" + pracId);
        try {
        Integer iPcislo = Integer.parseInt(pracId.toString());
        }
        catch (NumberFormatException ex) {
            return "ERR_getUdrzbar (iPracId)_" + pracId;
        }
        String gry = "SELECT PRIEZPR + ' ' + MENOPR as retval FROM PRAC WHERE ID = " + pracId;
        Object rtv = MyCn.getDbDriver().SQL_getQueryAsValue(MyCn.getConn(), gry, true);
        return rtv.toString();
    }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private eoc.widgets.DTXfield dTX_c_subj_zavady;
    private eoc.widgets.DTXfield dTXfield1;
    private eoc.widgets.DTcomboBox dTcb_c_popis_zavady;
    private eoc.widgets.DTcomboBox dTcb_c_subj_zavady;
    private eoc.widgets.DTcomboBox dTcomboBox1;
    private eoc.widgets.DTfield d_dtf_d_den_hlasenia;
    private eoc.widgets.DTfield d_dtf_d_den_hlasenia1;
    private eoc.widgets.DTtextArea dta_c_pozn_udrzbara;
    private eoc.widgets.DTfield dtf_c_cas_do;
    private eoc.widgets.DTfield dtf_c_cas_od;
    private eoc.widgets.DTfield dtf_c_meno;
    private eoc.widgets.DTfield dtf_c_navstiveny;
    private eoc.widgets.DTfield dtf_c_popis_zavady;
    private eoc.widgets.DTfield dtf_i_PorCisZaDen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
