package tipos;


import java.io.File;
import java.io.IOException;
import java.text.DecimalFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import jxl.Cell;
import jxl.CellType;
import jxl.Sheet;
import jxl.Workbook;
import jxl.WorkbookSettings;
import jxl.read.biff.BiffException;
import jxl.write.Label;
import jxl.write.WritableCellFormat;
import jxl.write.WritableSheet;
import jxl.write.WritableWorkbook;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author rvanya
 */
public class frm_Tipos_V3 extends javax.swing.JFrame {
    @Override
    public void setTitle(String title) {
        super.setTitle(title); //To change body of generated methods, choose Tools | Templates.
    }
  private File inputFile = new File("D:\\EaSys\\tipos\\loto5z35_2013_14.xls");
  private String cellFilter[] = {"A","B","C","D","E","F"};
//  private String columns[] = {"Dátum","č.1","č.2","č.3","č.4","č.5","Prognosis"};
  private /* MyTableModel */ DefaultTableModel tbmodelXLS;
  private Double wins[];
  
  /*
  class MyTableModel extends DefaultTableModel {
 
    @Override
      public Class getColumnClass(int col) {
        if (col > 0)       // treti stlpec je desatinne cislo
            return Integer.class;
        else return String.class;  // ostatne stlpce su textove
    }
 
    }
*/
    /**
     * Creates new form frm_Tipos
     */
    public frm_Tipos_V3() {
         wins = new Double[3];
         wins[0] = 8500.00;
         wins[1] = 490.00;
         wins[2] = 20.00;
//       updateTblModel(tbmodelXLS,columns);

        initComponents();
         this.setTitle("V3");
         tbmodelXLS = (DefaultTableModel) jTable_XLS.getModel(); // new MyTableModel();
        jTable_XLS.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);

        jTable_XLS.setModel(tbmodelXLS);
}
/*    
    private void updateTblModel(DefaultTableModel tblModel, String columns[]) {
        for (int i = 0; i < columns.length; i++) {
            tblModel. .addColumn(columns[i]);
        } 
    }
*/
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Dlg_FileChooser = new javax.swing.JDialog();
        jFileChooser1 = new javax.swing.JFileChooser();
        jTF_inputFile = new javax.swing.JTextField();
        jButton_XLS_File = new javax.swing.JButton();
        jButton_Nacitaj = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_XLS = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        cbTestedRows = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        cbOdhadnut = new javax.swing.JComboBox();

        Dlg_FileChooser.setAlwaysOnTop(true);
        Dlg_FileChooser.setMinimumSize(new java.awt.Dimension(604, 448));
        Dlg_FileChooser.setModal(true);

        javax.swing.GroupLayout Dlg_FileChooserLayout = new javax.swing.GroupLayout(Dlg_FileChooser.getContentPane());
        Dlg_FileChooser.getContentPane().setLayout(Dlg_FileChooserLayout);
        Dlg_FileChooserLayout.setHorizontalGroup(
            Dlg_FileChooserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 604, Short.MAX_VALUE)
        );
        Dlg_FileChooserLayout.setVerticalGroup(
            Dlg_FileChooserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 448, Short.MAX_VALUE)
        );

        jFileChooser1.setCurrentDirectory(new java.io.File("D:\\EaSys\\Tipos"));
        jFileChooser1.setMinimumSize(new java.awt.Dimension(586, 377));
        jFileChooser1.setOpaque(true);
        jFileChooser1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFileChooser1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTF_inputFile.setText("D:\\EaSys\\tipos\\loto5z35.xls");
        jTF_inputFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF_inputFileActionPerformed(evt);
            }
        });

        jButton_XLS_File.setText(" XLS súbor");
        jButton_XLS_File.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_XLS_FileActionPerformed(evt);
            }
        });

        jButton_Nacitaj.setText("Načítaj");
        jButton_Nacitaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_NacitajActionPerformed(evt);
            }
        });

        jTable_XLS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Den", "C1", "C2", "C3", "C4", "C5", "prognozis", "pocet", "suma"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_XLS.setColumnSelectionAllowed(true);
        jTable_XLS.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable_XLS);
        jTable_XLS.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (jTable_XLS.getColumnModel().getColumnCount() > 0) {
            jTable_XLS.getColumnModel().getColumn(0).setResizable(false);
            jTable_XLS.getColumnModel().getColumn(1).setResizable(false);
            jTable_XLS.getColumnModel().getColumn(1).setPreferredWidth(30);
            jTable_XLS.getColumnModel().getColumn(2).setResizable(false);
            jTable_XLS.getColumnModel().getColumn(2).setPreferredWidth(30);
            jTable_XLS.getColumnModel().getColumn(3).setResizable(false);
            jTable_XLS.getColumnModel().getColumn(3).setPreferredWidth(30);
            jTable_XLS.getColumnModel().getColumn(4).setResizable(false);
            jTable_XLS.getColumnModel().getColumn(4).setPreferredWidth(30);
            jTable_XLS.getColumnModel().getColumn(5).setResizable(false);
            jTable_XLS.getColumnModel().getColumn(5).setPreferredWidth(30);
            jTable_XLS.getColumnModel().getColumn(6).setResizable(false);
            jTable_XLS.getColumnModel().getColumn(6).setPreferredWidth(180);
            jTable_XLS.getColumnModel().getColumn(7).setResizable(false);
            jTable_XLS.getColumnModel().getColumn(8).setResizable(false);
        }

        jButton1.setText("Vyhodnoť");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        cbTestedRows.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        cbTestedRows.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTestedRowsActionPerformed(evt);
            }
        });

        jButton2.setText("Ullož");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        cbOdhadnut.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "5", "6", "7", "8", "9", "10", "11", "12", "13", "14" }));
        cbOdhadnut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbOdhadnutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 926, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTF_inputFile, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_XLS_File, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_Nacitaj)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbTestedRows, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbOdhadnut, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(66, 66, 66))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTF_inputFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_XLS_File)
                    .addComponent(jButton_Nacitaj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1)
                    .addComponent(cbTestedRows, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2)
                    .addComponent(cbOdhadnut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private String getPrognosisForRow(int rw) {
        Integer iTestedRows = 1;
        Integer iOdhadnut = Integer.parseInt(cbOdhadnut.getSelectedItem().toString());
        String ex = "";
        String pr = "";
        int cnt = 35;
        
        wblock:
        while (cnt > iOdhadnut) {
            ex = "";
            pr = "";
            cnt = 0;
            cntblock:
            for (int e = rw - 1; e >= rw - iTestedRows; e--) { // prechod pola iBefore
                if (e <= 0 || iTestedRows >= rw) {
                    cnt = iOdhadnut;
                    continue wblock;
                    //break cntblock;
                }
                for (int d = 0; d < 5; d++) { // prechod riadku pola iBefore
                     ex = ex + "," + tbmodelXLS.getValueAt(e,d + 1);
                } 
            }
            ex = ex + ",";
            System.out.println(rw + " -- " + ex);
            for (int p = 1; p <= 35; p++) {
                if (!ex.contains("," + p + ",")) {
                    cnt++;
                    pr = pr + "," + p;
                }
            }
            if (cnt > iOdhadnut) iTestedRows++;
        }
        pr = pr + ",";
        pr = "(" + cnt + ") " + pr;
        pr = testPr(rw,pr) + " " + pr;
        return pr;
    }
    private String testPr(int rw, String pr) {
       int ex = 0;
       for (int d = 0; d < 5; d++) { // prechod riadku pola iBefore
           if (pr.contains(","+ tbmodelXLS.getValueAt(rw,d + 1) + ","))
               ex++;
       } 
       return ex < 3 ? "---" : "[" + ex + "]"; 
    }
    private void jButton_XLS_FileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_XLS_FileActionPerformed
        jFileChooser1.showDialog(Dlg_FileChooser, "Výber prvého súboru XLS");
        inputFile = jFileChooser1.getSelectedFile();
        if (inputFile!=null) {
        jTF_inputFile.setText(inputFile.getAbsolutePath());
    }
        //}

    }//GEN-LAST:event_jButton_XLS_FileActionPerformed

    private void jButton_NacitajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_NacitajActionPerformed
        try {
            readXLS(inputFile, cellFilter, tbmodelXLS);
        } catch (IOException ex) {
            Logger.getLogger(frm_Tipos_V3.class.getName()).log(Level.SEVERE, null, ex);
        } catch (BiffException ex) {
          Logger.getLogger(frm_Tipos_V3.class.getName()).log(Level.SEVERE, null, ex);
      }
       // spojXLS();
    }//GEN-LAST:event_jButton_NacitajActionPerformed
    public void readXLS(File inputFile,String cellFilter[],DefaultTableModel tbmodel)
           throws IOException, BiffException  {
    File inputWorkbook = inputFile;
    Workbook w;
    WorkbookSettings ws = new WorkbookSettings();
    ws.setEncoding( "cp1250" );
    boolean showDataType = true;
    try {
      w = Workbook.getWorkbook (inputWorkbook, ws);
      // zistim prvu stranu XLS suboru
      Sheet sheet = w.getSheet(0);
      // Hodnoty, ktore potrebujeme
      DecimalFormat df = new DecimalFormat("0");
      //Integer spolu = new Integer(0);
      int rowCount = 0;
      for (int i = 2; i <= sheet.getRows(); i++) {
          Object[] oRowData = new Object[cellFilter.length];   
//         krn.OutPrintln("CLL" + cellFilter.length);
          for (int j = 0; j < cellFilter.length; j++) {
              Cell myCell = sheet.getCell(cellFilter[j] + i);
              CellType type = myCell.getType();

              if (type == CellType.LABEL) {
 //           System.out.print((showDataType ? "# LBL:" : "") + celll.getContents());
                  oRowData[j] = new String(myCell.getContents());
              }
              else if (type == CellType.NUMBER) {
 //           System.out.print((showDataType ? "# NUM:" : "") + celll.getContents());
                  oRowData[j] = new Integer(myCell.getContents().replace(',','.'));
                  //spolu = spolu + (Integer) oRowData[j];
              }
              else if (type == CellType.DATE) {
//            System.out.print((showDataType ? "# DAT:" : "") + celll.getContents());
//            oRowData[j] = new Date(celll.getContents());
                  oRowData[j] = new String(myCell.getContents());
              }
              else {
//            System.out.print((showDataType ? "# ???:" : "") + celll.getContents());
                  oRowData[j] = new String(myCell.getContents());
              }
          //System.out.print(";" + cell.getContents() 
          //+ "[" + type.toString() + "]"
          // );
        }
//        krn.OutPrintln("");
        tbmodel.addRow(oRowData);
        rowCount++;
      }
      // krn.OutPrintln("Spolu v " + inputFile.getName() + "  -> riadokov: " + rowCount + " suma spolu: " + spolu);
      
    } catch (BiffException e) {
      e.printStackTrace();
    }
  } // public void readXLS(File inputFile, DefaultTableModel tbmodel)

    
    private void jFileChooser1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFileChooser1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFileChooser1ActionPerformed

    private void jTF_inputFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTF_inputFileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTF_inputFileActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        vyhodnotit();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cbTestedRowsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTestedRowsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTestedRowsActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        saveData();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cbOdhadnutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbOdhadnutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbOdhadnutActionPerformed

    public void saveData(/* JTable table, File file */){
        try{
           File outputFile = new File(jTF_inputFile.getText().replace(".", "_saved.")); 
           WritableWorkbook workbookSave = Workbook.createWorkbook(outputFile);
           WritableSheet sheetSave = workbookSave.createSheet("Vyhodnotné data", 0);
           WritableCellFormat wcf = new WritableCellFormat();

            //DefaultTableModel model = tbmodelXLS3;
            for (int i = 0; i < tbmodelXLS.getColumnCount(); i++) {
                Label column = new Label(i, 0, tbmodelXLS.getColumnName(i));
                sheetSave.addCell(column);
            }
            int j = 0;
            for (int i = 0; i < tbmodelXLS.getRowCount(); i++) {
/*        
  private String columns_Z[] = {"VS","Meno","Ulica","1","2","3","Suma20140331"
                                ,"Suma20150331","RozdVyuct","ZostPredVyu"
                                ,"ZostPoVyu"};
*/        
                for (j = 0; j < tbmodelXLS.getColumnCount(); j++) {
                    // textove stlpce
                    if (j < 6) {
                       Label row = new Label(j, i + 1,
                               getNotNULLstring(tbmodelXLS.getValueAt(i, j)));
                       sheetSave.addCell(row);
                    }
                    // desatinne cisla
                    else {
                    jxl.write.Number number 
                       = new jxl.write.Number(j, i + 1, getNotNULLdouble(tbmodelXLS.getValueAt(i, j)));
                    /*
                    WritableCell wrc = new WritableCell();
                            new Number(j, i,
                            getNotNULLdouble(tbmodelXLS3.getValueAt(i, j)));
                      */
                    sheetSave.addCell(number);
                        
                    }
                }
            }
            workbookSave.write();
            workbookSave.close();
        }catch(Exception ex){
            ex.printStackTrace();
        }
    }
    
    private String getNotNULLstring (Object o) {
        return ((o == null) ? "" : o.toString());
    }

    private Double getNotNULLdouble (Object o) {
        Double db = new Double(0);
        if (o == null) o = "0";
        String v = o.toString();
        if (v.toString().indexOf(".") > 0)
            v = v.substring(0, (o.toString().indexOf(".") - 1));
        try {
        db = (o == null) ? 0.00: (double) (Integer.parseInt(v));
        }
        catch  (Exception ex) {
            System.out.println("EXC-ON " + o.toString());
        }
        return db;
    }

    /**
     * @param args the command line arguments
     */
    
    public void vyhodnotit() {
        Integer iTestedRows = Integer.parseInt(cbTestedRows.getSelectedItem().toString());
        Integer[][] iBefore = new Integer[iTestedRows][5];
        Integer[]   iAktRow = new Integer[5];
        Integer     iExists = 0;
        for (int i = 0; i < tbmodelXLS.getRowCount(); i++) {
            if (i < iTestedRows) { // doplnuje sa len iBefore
                for (int e = 0; e < 5; e++) {
                    iBefore[i][e] = (Integer) tbmodelXLS.getValueAt(i,e + 1);
                }
            }
            else { // vyhodnotenie + zapis vyhodnotenia + posun iBefore o riadok
                String prg = getPrognosisForRow(i);
                tbmodelXLS.setValueAt(prg, i, 6);  // Prognoza
                
                for (int e = 0; e < 5; e++) {
                    iAktRow[e] = (Integer) tbmodelXLS.getValueAt(i,e + 1);
                }
                
                iExists = 0;
                for (int e = 0; e < iTestedRows; e++) { // prechod pola iBefore
                    for (int d = 0; d < 5; d++) { // prechod riadku pola iBefore
                        for (int a = 0; a < 5; a++) { // prechod aktualneho riadku
                            if (iAktRow[a].equals(iBefore[e][d])) {
                               iExists++;
                            }
                        }
                    }
                }
                
                // posun pola iBefore hore
                for (int e = 1; e < iTestedRows; e++) { // prechod pola iBefore
                    for (int d = 0; d < 5; d++) { // prechod riadku pola iBefore
                       iBefore[e - 1][d] = iBefore[e][d];
                    }
                }    
                // pridanie iAktRow do IBefore
                for (int d = 0; d < 5; d++) {
                    iBefore[iTestedRows - 1][d] = iAktRow[d];
                }
                /*
               tbmodelXLS.setValueAt(iExists, i, 6);
               if (iExists < 3) {
                 int iCena = iExists + 1;  
                 tbmodelXLS.setValueAt(iCena, i, 7);
                 tbmodelXLS.setValueAt(wins[iCena - 1], i, 8);
               }
               else {
                  tbmodelXLS.setValueAt("", i, 7);
                 tbmodelXLS.setValueAt("0", i, 8);
               }
               tbmodelXLS.setValueAt("7", i, 9);  // Price/cena
                */
            }
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_Tipos_V3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_Tipos_V3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_Tipos_V3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_Tipos_V3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_Tipos_V3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog Dlg_FileChooser;
    private javax.swing.JComboBox cbOdhadnut;
    private javax.swing.JComboBox cbTestedRows;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton_Nacitaj;
    private javax.swing.JButton jButton_XLS_File;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTF_inputFile;
    private javax.swing.JTable jTable_XLS;
    // End of variables declaration//GEN-END:variables
}
